### ISSUE TITLE
Hello, what is the rule of data used in this SDK?  littleEndian or bigEndian？Both?

### ISSUE THREAD

**Issue by trusbe** [NordicSemiconductor/IOS-nRF-Mesh-Library#100]
When we extend the SDK, we need to follow the rules of the SDK to expand. What rules are used in the SDK (including Android and firmware)?

**Comment by mostafaberg** [comment]
There's no single rule for that, It's best to look at specific messages/functionality that you'll implement then verify from the mesh spec if it's little/big endian, it can be different depending on message types, etc ...

**Comment by trusbe** [comment]
got it, I read the SIG related documentation, all Messages and parameters need to use little endian, thank you .
