### ISSUE TITLE
Changing the Models names

### ISSUE THREAD

**Issue by ManishSudini** [NordicSemiconductor/IOS-nRF-Mesh-Library#103]
Hi,

I would like to customize the names of the Generic OnOff models (Client and Server) in the nRF Mesh App after the devices are provisioned. 

How can I do that?

Thank you.

**Comment by mostafaberg** [comment]
That actually sounds like a bad idea, GenericOnOff is _the_ name of the model, you shouldn't change SIG defined model names.
If you need a custom name, I recommend creating your own vendor model Identifier and then use that instead with whatever name you choose.

However, to answer your question, the names and identifiers are defined [here](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/58e5ed76a8fda9972e31cfeec81543ae27ff5646/nRFMeshProvision/Classes/Models/MeshModelIdentifiers.swift#L18-L19)

and the equivalent strings can be found [here](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/58e5ed76a8fda9972e31cfeec81543ae27ff5646/nRFMeshProvision/Classes/Models/MeshModelIdentifierStringConverter.swift#L20-L21)

simply change the names in the string to whatever you want it to be :), however, I highly discourage that, but it's ok for a quick demo :)

**Comment by ManishSudini** [comment]
Hi, 
Yes, I understand that it is a very bad idea but we just want to change it temporarily till we have generic level model running perfectly. After we have that, we are planning to create a vendor model as you said.

Thank you for the response.
