### ISSUE TITLE
How to configure a proxy node from the app so that we can communicate to any node, from the app, with the state change (For example, Generic Server ON/OFF)

### ISSUE THREAD

**Issue by MukteshManju** [NordicSemiconductor/IOS-nRF-Mesh-Library#104]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mostafaberg** [comment]
Good morning @MukteshManju !, I think you'll get more tips if you ask on https://devzone.nordicsemi.com as this is a general question not an issue in the library.
