### ISSUE TITLE
GenericOnOff State always return false/00

### ISSUE THREAD

**Issue by bhavik-volansys** [NordicSemiconductor/IOS-nRF-Mesh-Library#106]
In Mesh library we have one class to get the state of OnOff but it always return the false/00 state. I have also checked with Andorid library and also on your application for that and in that also same issue happnes.

GenericOnOffGetControllerState.swift

**Comment by mostafaberg** [comment]
Could it be an issue with the firmware since it reproduces on Android and iOS ?

**Comment by philips77** [comment]
Hi, did you manage to solve the issue?
