### ISSUE TITLE
Generic Level model values range goes only until about 3%

### ISSUE THREAD

**Issue by PM-BubblyNet** [NordicSemiconductor/IOS-nRF-Mesh-Library#108]
Hi,
When using the iOS app to control the dimming example on meshSDK/examples/experimental_dimming/dimming server the range goes from 0% to about 3% only then setting level to 100% (we changed the pin polarity btw, but the same happens on the stock example).
This happens only on the iOS app, the android app works ok with the generic level.
iOS app:
![1547218756586](https://user-images.githubusercontent.com/38331043/51041307-a08eeb80-1587-11e9-9d2b-e67f6dd0f8a1.JPEG)
Android app:
![1547218325754](https://user-images.githubusercontent.com/38331043/51041308-a08eeb80-1587-11e9-8b67-fe28abb5a286.JPEG)
Thanks!

**Comment by zanibonilighting** [comment]
Hi again!

So I found a weird conversion on ⁨IOS_App⁩ ▸ ⁨Example⁩ ▸ ⁨nRFMeshProvision⁩ ▸ ⁨ViewControllers⁩ ▸ ⁨NodeConfigurationView⁩ ▸ ⁨ModelConfigurationView⁩ ▸ ⁨didChangeSliderOnCell line 948:

var level = Int(((newSliderValue * 65535) / 100) - 32768)

I don't see why the / 100… anyways I removed and now it seems we have a full range from -32768 to +32768… but I dont know why the developer made that conversion and I dont know which test to run so we cant be sure I didn’t just bring a tons of bugs… so I think to leave this question open for now until someone with a bit more experience with the app can confirm the hot fix...

**Comment by roshanrajaratnam** [comment]
Hi @zanibonilighting thanks for reporting this issue I see what the problem here is. The slider value is from ranges from 0.0 - 1.0 so I guess the mistake was the division by 100 forgetting the slider does not range from 0-100. Nice catch!

**Comment by zanibonilighting** [comment]
awesome!

**Comment by roshanrajaratnam** [comment]
I would leave it open until we fix this, although we welcome pull requests. If you would like you can contribute towards the library! All you have to do is to sign the CLA when sending a pull request :tada:

**Comment by philips77** [comment]
Closing the issue as the old version is no longer maintained. This should work fine in the new version.
