### ISSUE TITLE
object-C

### ISSUE THREAD

**Issue by Marcello168** [NordicSemiconductor/IOS-nRF-Mesh-Library#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by philips77** [comment]
Hi, please follow the steps described here: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/documentation.md#integration (this is about DFU Library, but the method should be similar).
This library is written in Swift but can be included Objective-C projects.
