### ISSUE TITLE
receivedModelPublicationStatus and receivedModelSubsrciptionStatus called multiple times

### ISSUE THREAD

**Issue by bhavik-volansys** [NordicSemiconductor/IOS-nRF-Mesh-Library#110]
We are trying to create a group and for that, we need to subscribe and publish to some particular group id like "C001" for on/off model. When we subsribe to id "C001" the delegate method

`func receivedModelPublicationStatus(_ modelPublicationStatusData: ModelPublicationStatusMessage)`

 is calling almost 3-4 times and it's not fixed so is there any way that we can find some index or something to find the last packet or any other workaround?

Please guide us for this

**Comment by philips77** [comment]
Hi,
Few questions:
1. Is the delegate called once after subscribing only one device, twice after the second etc.?
2. Do you get those callback during subscription or when sending a message to the group? Are you publishing acknowledged messages? Perhaps you are getting a callback from each node that had received the command?
3. Are you using the sample app or trying to include the lib in your project? 
4. Did you do any further debugging and have more information?

Sorry, I can't help more at the moment :( I'm not the author of this library.

**Comment by bhavik-volansys** [comment]
1. Is the delegate called once after subscribing only one device, twice after the second etc.?
> Not, it is calling delegate method multiple times for single device only

2. Do you get those callback during subscription or when sending a message to the group? Are you publishing acknowledged messages? Perhaps you are getting a callback from each node that had received the command?
> During subscription.

3. Are you using the sample app or trying to include the lib in your project?
> I have tried on both the application. Sample app and also integrated into our app

4. Did you do any further debugging and have more information?
> If you want then I can share the logs but that will be encrypted.

**Comment by philips77** [comment]
Thanks,
I talked with the author of this library, who unfortunately has transition to new tasks, and he suggests that the device may send multiple responses to subscription request (retransmission?). Perhaps the phone does not ack that it received the message?
Until we assign more resources to the app I sorry but I can't help you more. Could you dig on your own and prepare a PR with possible fix?

**Comment by bhavik-volansys** [comment]
Hi,
We are kind of stuck now, we have tried to find a way to check for the last packet but we are not able to find that. We just want to know that how we can identify that delegate method `receivedModelPublicationStatus` will not call now?

**Comment by philips77** [comment]
Closing the issue as the old version is no longer maintained. Please try the new version which, I hope, does not have this issue.
