### ISSUE TITLE
Single publish and subsribe for On/Off and Level model

### ISSUE THREAD

**Issue by bhavik-volansys** [NordicSemiconductor/IOS-nRF-Mesh-Library#111]
We want to subscribe and publish on both models on/off and level so we have to make total of 4 calls for a single device. Publish/subscribe for on/off [0x10, 0x00] and publish/subscribe for level [0x10, 0x02]. If we want to add 10 devices in C001 then we have to call 40 calls.

**Comment by philips77** [comment]
Hello again!

We know manual network configuration is a pain, but this app is mainly a sample app for the library. It is not design with amazing UX in mind, but rather development simplicity. Setting up groups would rather require fancy UI, drag and drops, etc, and we have no resources for it, unfortunately.

We may keep the issue open as a reminder but it's highly unlikely we can implement this in near future.

**Comment by bhavik-volansys** [comment]
Hi @philips77,

Thanks for your reply,

I understand that this is just a sample app so I am not suggesting to have some fancy UI or UX. My concern is if we want to add 10 devices to a single group than we have to call

`nodePublicationAddressSet`
`nodeSubscriptionAddressAdd`

for both the models

`let aModel = Data(bytes: [0x10, 0x00]) //OnOff Model`

`let aModel = Data(bytes: [0x10, 0x02]) // Level Model`

so is there any way so we can have combine calls for both the models or some other way?

**Comment by philips77** [comment]
I don't think so. They have to be sent as 2 packets anyway, as they target 2 different models. I think it's only a matter of UI.
@roshanrajaratnam ?
