### ISSUE TITLE
Groups implementation

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/IOS-nRF-Mesh-Library#117]
**Is your feature request related to a problem? Please describe.**
We are implementing the groups into the UI already and we have an open question, when adding a new item to the group, should this "item" be a whole element with all its models? or should every model be added separately? lets say that we have a server with an on/off model and generic level model, should both models be added to the group automatically or should every model be added separately?

**Describe the solution you'd like**
Complying with the specification and standard

**Describe alternatives you've considered**
We are not sure what the specification or standard should be, all the models inside an element should be added to the group or not?

**Additional context**

**Comment by philips77** [comment]
This feature is coming soon in the currently developed second version of the lib/sample app. I'll close the issue when it's finished.

**Comment by philips77** [comment]
Group controls are now working. From the sample app we implemented only Generic OnOff and Generic Level models, but they are enough for now.

Answering your questions:

> should this "item" be a whole element with all its models? or should every model be added separately?

You subscribe models to groups, so we decided to display them. If there are multiple App Keys bound to such model, we also allow users to send messages using selected one of them, as they may target different devices. For example all Generic OnOff may be in the "Kitchen" group, you you control lights and power plugs separately.

> lets say that we have a server with an on/off model and generic level model, should both models be added to the group automatically or should every model be added separately?

You add each model separately, at least no the very low level, where you send messages. How you display it in your app for the user it's a different story and you should focus on best UX.
