### ISSUE TITLE
Can't paste a key in "App Keys" tab. 

### ISSUE THREAD

**Issue by kaiser-ren** [NordicSemiconductor/IOS-nRF-Mesh-Library#122]
**Describe the bug**
Below is the key I'd like to paste on nRF Mesh App, "App Keys" tab. 
*68eed9c2a56add85049ffc3c59ad0c1f*
"Enter a key name", I input a short name, "a".
"Paste value or tap 'generate' ", I pasted value, but this textbox is empty and I can't click "Save" button because it's gray. 

**Platform details:**
 - Device: iPhone8
 - OS: 12.2
 - Library Version: v1.0.4, build 12

**Comment by philips77** [comment]
Closing the issue as the old version is no longer maintained.
