### ISSUE TITLE
Is there a way to listen to the ON/OFF state of the light on the proxy server node from the app?

### ISSUE THREAD

**Issue by heywil** [NordicSemiconductor/IOS-nRF-Mesh-Library#123]
Hi, 
I have set up a proxy client as a switch and a proxy server as a light, and able to switch the light on off with the client button. 
I would like to display different UI on the app when the light is ON or OFF. I found the android sample app was able to listen to the proxy and get callback when the light changes, but I was not able to find this function in the sample program. 
I also was not able to find related code in the library. 
Please help. Many thanks.

**Comment by philips77** [comment]
Hi, I'm in a process of rewriting the iOS Mesh Lib to be more similar to Android one (transport independent). This will take few months, I suppose, before it's ready. It will for sure have more features, but currently it's in a very early stage. Follow branch `version2`.
