### ISSUE TITLE
Question: JSON import/export

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/IOS-nRF-Mesh-Library#129]
Hello,

I was wondering if the JSON files will be able to be imported and exported and shared between both iOS and Android? Right now some of the properties are different and importing between the two does not work. I know it is not finished but will this be possible?

**Comment by philips77** [comment]
Did you try version from branch "version2"? There the json files should be compatible. If you find any issue, please report here.

**Comment by BubblyNetDev** [comment]
It was a problem with an older version of the Android we were using. Everything worked well today. Thanks.
