### ISSUE TITLE
After reset (un-provisioning), the node is not able to discover for further Provisioning

### ISSUE THREAD

**Issue by sunilloharshoreline** [NordicSemiconductor/IOS-nRF-Mesh-Library#131]
Once the node is reset or de-provisioned , it is not able to rediscover.

**Comment by philips77** [comment]
Which version of the library are you using? From*master*, or the new one from *version2* branch? The new one works for me.
Also, the behavior or reset depends on the firmware side. It should de-provision itself, but perhaps it doesn't. 
Resetting it supported correctly in Nordic mesh sdk 3.1, but should work with older versions as well. I've tested it also with Zephyr and also works.

**Comment by sunilloharshoreline** [comment]
I was using master and tried with version2 as well, the problem identified was from firmware side. 
Thanks for reply.
