### ISSUE TITLE
Group Setting Subscription

### ISSUE THREAD

**Issue by BubblyNetIntegration** [NordicSemiconductor/IOS-nRF-Mesh-Library#132]
Question:

Hey Aleksander I just wanna say welcome back, hope you enjoyed your time off. Quick question. When do you think Group Setting Subscription will be done? We can't wait to start working on it. 

The app is looking very good, congrats!

**Comment by philips77** [comment]
I've started working on groups on Tuesday. I still need to polish the API. Next step is adding them to publication and implementing subscription. I guess next week it should all work.
Btw, I'm still on vacation, just coding while enjoying 🌞 ;)

**Comment by BubblyNetIntegration** [comment]
@philips77 😅😅😅
Thanks for the quick answer though!! Enjoy the rest of your vacation!

**Comment by philips77** [comment]
Hi, subscriptions should be working now. First, create groups, then you may use them in Publications and Subscriptions in Models. I didn't implement Subscription List and Get messages yet, but the rest should work.

**Comment by BubblyNetIntegration** [comment]
@philips77 fantastic, thanks for the update!

**Comment by philips77** [comment]
Ups, I forgot to push one file that's needed for Subscriptions. I just pushed all the changes, so everything should finally work now.

**Comment by philips77** [comment]
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/commit/97f24a203c46213da77e33ef8c657449133fccb2
