### ISSUE TITLE
Question Provision Failed in Version 2

### ISSUE THREAD

**Issue by Marcello168** [NordicSemiconductor/IOS-nRF-Mesh-Library#134]

**Comment by Marcello168** [comment]
![Look This](https://s2.ax1x.com/2019/07/31/etav5j.jpg)

**Comment by philips77** [comment]
Yes, I know. It has already been reported in #61. I'll fix it asap.

**Comment by philips77** [comment]
This should now be fixed with the latest changes. Could you give it a spin?

**Comment by Marcello168** [comment]
ok ，I'll give it a try.

**Comment by Marcello168** [comment]
hello,the latest version works OK,but it have a new pro problem @philips77
