### ISSUE TITLE
Can not add the application key to the generic onoff model 

### ISSUE THREAD

**Issue by Marcello168** [NordicSemiconductor/IOS-nRF-Mesh-Library#135]
**Describe the bug**
can not add the application key to the generic onoff model as the picture shows

**To Reproduce**
1. I' created an application key in the Settings as the  first picture shows
2. when I in generic onoff model  Page  to click Bind Application key ,but it shows  NO KEYS AVAILABLE

**Expected behavior**
Can  add the application key to the generic onoff model

**Platform details:**
 - Device: iPhoneSE
 - OS: iOS10.1
 - Library Version :version 2

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster
[![erhpV0.jpg](https://s2.ax1x.com/2019/08/03/erhpV0.jpg)](https://imgchr.com/i/erhpV0)
[![erhC5T.jpg](https://s2.ax1x.com/2019/08/03/erhC5T.jpg)](https://imgchr.com/i/erhC5T)
[![erh9aV.jpg](https://s2.ax1x.com/2019/08/03/erh9aV.jpg)](https://imgchr.com/i/erh9aV)

**Comment by philips77** [comment]
Hi, it's not a bug. First, you have to go back to Node screen, where you'll find Network Keys and Application Keys. Add the desire Network Keys, than Application Keys. This will actually send the keys to the node. Only then go to the model and you'll find the app keys known to the node in the Bind Application Key section.
I'll make this more clear in the UI. Thank you for the feedback.
