### ISSUE TITLE
Controlling in Version 2

### ISSUE THREAD

**Issue by sunilloharshoreline** [NordicSemiconductor/IOS-nRF-Mesh-Library#137]
Is there any support for controlling any Model either Individual or Group (looks like there is no support from Group :  https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/issues/116  , but is Individual control available)  ?

**Comment by philips77** [comment]
Hi, not yet. 
Both individual and group control should be added very soon. Next week or two.

**Comment by sunilloharshoreline** [comment]
Thanks for the update.

**Comment by BubblyNetIntegration** [comment]
Hello @philips77. I hope you enjoying your vacation. 
Any idea of when the controllers will be implemented?
Thanks!

**Comment by philips77** [comment]
I'm implementing controls for Vendor Models right now. Generic On/Off will follow, then those 2 in Groups.

**Comment by philips77** [comment]
Vendor Messages can be now sent from the UI. Go to Node -> Element -> Vendor Model -> Controls. Tested using Zephyr implementation.

**Comment by sunilloharshoreline1** [comment]
Hi @philips77 , i checked in the latest code pushed to repo, there are compile errors in MeshMessage.swift file for extension CustomDebugStringConvertible. The error says : Extension of protocol 'CustomDebugStringConvertible' cannot have an inheritance clause
Can you look into it ?
Thanks.

**Comment by philips77** [comment]
Oh, sure. I'll have a look at it now.

**Comment by philips77** [comment]
Done. Sorry, that was stupid. Next time I'll try at least to compile before pushing changes ;)

**Comment by sunilloharshoreline1** [comment]
Thanks for the quick fix. I m able to compile successfully but as you mentioned the vendor messages can be sent through UI , i didn't find anything on UI for this. What i did was :  first i provisioned the node and then Assigned App Key and Subscription to the Model (Generic On Off).
Am i missing something ?
Here is the screenshot :
![version2-control](https://user-images.githubusercontent.com/54349293/63418081-1ca3b880-c420-11e9-847f-35bdd46189e7.PNG)

**Comment by philips77** [comment]
Generic ON/Off will be added shortly. Currently you'd see a custom UI at the bottom for Vendor Models.
If you want to test it, here's the Sample On Off app (Client and Server) for nRF52832 DK.
[Mesh SDK 3.2 Simple On Off.zip](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/files/3525075/Mesh.SDK.3.2.Simple.On.Off.zip)
Here you'll find some documentation about the supported messages: https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.meshsdk.v3.2.0/md_models_vendor_simple_on_off_README.html?cp=5_2_2_3_1

**Comment by philips77** [comment]
Generic OnOff Server controls should be in place right now if you pull the latest changes.

**Comment by philips77** [comment]
I'm closing the issue, as Generic OnOff, Generic Level and Vendor Models can be configured from the UI now. The 2 first can be also controller from the Group level.
