### ISSUE TITLE
MeshNetworkDelegate not included in source files by Podspec

### ISSUE THREAD

**Issue by y0sh33** [NordicSemiconductor/IOS-nRF-Mesh-Library#139]
The podspec includes files in nRFMeshProvision/Classes but the file MeshNetworkDelegate.swift is located in the root folder of the repo. Seems like that file should also be in the nRFMeshProvision/Classes folder (and Example project file updated accordingly)?

**Comment by philips77** [comment]
Of course, sorry for that. Will fix it right away.
