### ISSUE TITLE
Configuration Messages - SIG Model

### ISSUE THREAD

**Issue by BubblyNetIntegration** [NordicSemiconductor/IOS-nRF-Mesh-Library#140]
I noticed that there is no ConfigSIGModelAppSet on the project yet. Are you planing to have it soon, or the generic set messages will be implemented differently? 

I also caught a file misspelling under the same package.

<img width="403" alt="Screen Shot 2019-08-21 at 9 02 15 AM" src="https://user-images.githubusercontent.com/52210132/63434419-09c6bf00-c3f3-11e9-8830-c91242ca4a12.png">

Thanks!

**Comment by philips77** [comment]
I'll fix the typo tomorrow, thanks. 
There is no ConfigSIGModelAppSet in the spec. You should use ConfigModelAppBind instead, for both SIG and Vendor models.
