### ISSUE TITLE
Provisioner unicast address range

### ISSUE THREAD

**Issue by BubblyNetIntegration** [NordicSemiconductor/IOS-nRF-Mesh-Library#144]
Any reason why on iOS, the provisioner unicast address follows the same numerical increment of the provisioned nodes? The Android sets its unicast automatically to 0x7FFF for the provisioner.

![IMG_CF0D473FC336-1](https://user-images.githubusercontent.com/52210132/63769959-14c19980-c8a2-11e9-98a4-234fc9f8b3f4.jpeg)

**Comment by philips77** [comment]
Yes, that's true. First of all, it was easier to implement, as there's no need to look for a slot from the end. Secondly, a provisioner is a normal node, so don't see a reason why would they need a different numbering.
