### ISSUE TITLE
Provisioned Node Models

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#145]
Hi,
I'm having trouble understanding how to use the library to get a populated array of Models for each node's element. Right after the provisioning it appears to have 1 element but no Models.

What I am doing wrong?

Thank You very much.

Marco

**Comment by philips77** [comment]
I think you managed to solve it, looking at #148, yes? Can we close this issue?

**Comment by fiveagle** [comment]
Yes Thanks
