### ISSUE TITLE
Problems in iOS13beta version

### ISSUE THREAD

**Issue by huahuali** [NordicSemiconductor/IOS-nRF-Mesh-Library#147]
Question 1: iOS13beta version, unable to connect to Bluetooth
Question 2: In the same iOS13beta version, Bar tint of large titles sets the custom color to be transparent.

**Comment by philips77** [comment]
Yes, the app isn't ready for iOS 13 yet. We'll fix it soon.

**Comment by huahuali** [comment]
ok，thanks
