### ISSUE TITLE
[CoreBluetooth] XPC connection invalid 

### ISSUE THREAD

**Issue by sunilloharshoreline1** [NordicSemiconductor/IOS-nRF-Mesh-Library#156]
Getting an : [CoreBluetooth] XPC connection invalid, if removed action on alert for the Cancel button from ScannerTableViewController.
The code I removed :
```swift
alert!.addAction(UIAlertAction(title: "Cancel", style: .cancel) { action in
    action.isEnabled = false
    self.alert!.title   = "Aborting"
    self.alert!.message = "Cancelling connection..."
    bearer.close()
})
```
or even though the line `bearer.close()` is commented or removed then the issue gets reproduced

**Comment by philips77** [comment]
Hi, did you manage to solve your issue?

**Comment by sunilloharshoreline1** [comment]
no luck so far. still getting the same error.

**Comment by philips77** [comment]
I think this error happens when the app looses reference to a `CBPeripheral` that is still not disconnected. I see in the code that we start disconnecting and immediately then forget the reference, which seems to generate this warning. Still, this is not a big issue, as the system can clean up on its own.

**Comment by philips77** [comment]
The log happens as the `CBCentralManager` is not held by a view controller, or that view controller is being released. When a strong reference to it is lost this message is printed. I think Apple wants us to use just one central manager per app? I don't think anything can be done with it. It doesn't break anything. This log can just be ignored.

In the nRF Mesh Provision library each bearer object holds its own central manager inside. Closing a bearer and loosing a reference to it causes this issue. Also, scanner for unprovisioned devices and for proxy nodes also use new instances of central manager and they drop it when the bearer is connected. Still no issue.
