### ISSUE TITLE
Can't not found elements

### ISSUE THREAD

**Issue by codepgq** [NordicSemiconductor/IOS-nRF-Mesh-Library#164]
I download latest code, i can provision device, but can't found elements.  if i use android phone, is work. Add Application Keys is not work.

![image](https://user-images.githubusercontent.com/20208598/65825879-d52a0b00-e2ae-11e9-9829-e22c6194e7dc.png)

![image](https://user-images.githubusercontent.com/20208598/65825909-4c5f9f00-e2af-11e9-9191-5f92fdda80b1.png)

'
![image](https://user-images.githubusercontent.com/20208598/65825913-508bbc80-e2af-11e9-81c7-cc5037547119.png)

**Comment by philips77** [comment]
Looks like your provisioner has disabled configuration (doesn't have unicast address assigned), thus it can't send messages to the network. 
Go to Settings, than Provisioners, click the local Provisioner and assign any available address from it's range.

**Comment by codepgq** [comment]
thanks，is work now
