### ISSUE TITLE
Configure disconnection timeout 

### ISSUE THREAD

**Issue by sunilloharshoreline1** [NordicSemiconductor/IOS-nRF-Mesh-Library#170]
The node gets disconnected after 1 minute if no action is performed. How can I configure and increase the timeout for disconnection ?

**Comment by philips77** [comment]
Are you taking about a Node with nRF Mesh firmware? You have to ask on DevZone, as this isn't related to the iOS library.

**Comment by sunilloharshoreline1** [comment]
Yes, the Node with nRF mesh Firmware. So, is the disconnection happens from iOS Library if no action performed?

**Comment by philips77** [comment]
No, the library isn't disconnecting. Ask if device l DevZone why would the node disconnect from z connected proxy.

**Comment by sunilloharshoreline1** [comment]
Thanks for the update.
