### ISSUE TITLE
From Configuration Server, the status alert stays there even if it is completed

### ISSUE THREAD

**Issue by icarus31** [NordicSemiconductor/IOS-nRF-Mesh-Library#172]
**Describe the bug**
When taping the 'Set Relay' button or pull down to refresh the page from Configuration Server, the alert shows up, but never disappears until the time out occurs.

**To Reproduce**
See above

**Expected behavior**
Alert disappears.

**Platform details:**
 - Device: iPhone 7
 - OS: 13.1.2
 - Library Version (or Commit): a0cd66

**Logs / Screenshots**
None

**Comment by philips77** [comment]
Hmm... I'll have to look into it. I'm on vacations now, so the next time I can do this is next Thursday.

**Comment by icarus31** [comment]
My fault. Not an issue anymore.
