### ISSUE TITLE
Unknow Message received after send

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#174]
**Describe the bug**
Hi,
after updating the pod yesterday I cannot successfully bind the App Key to the node models anymore. It used to work before updating the pod. I have tested on a different Mac with the previous commits. It happens on both  ConfigAppKeyAdd and ConfigCompositionDataGet

**To Reproduce**
Send a ConfigAppKeyAdd message to a Mesh Device

**Expected behavior**
To keep working as before or a more detailed error message

**Platform details:**
 - Device:  iPhone8
 - OS: iOS 12.3
 - Library Version: Last commit e9be842730a0c0ae472279aa8d7e90115dc90ade

**Logs / Screenshots**
Inside
```swift
meshNetworkManager(_ manager: MeshNetworkManager,
                   didReceiveMessage message: MeshMessage,
                   sentFrom source: Address, to destination: Address)
```
I get:
```swift
UnknownMessage(opCode: 0x000002, parameters: 00600701000000280003000000060100000200001003120412051260070100)
```

**Comment by philips77** [comment]
What if you set 'manager.localElements = []` after creating the manager? I think the issue may be if the local elements aren't set up. After assigning any value to it, including an empty array, this should work. Fit the reference, the sample app creates 2 elements in `AppDelegate`.

**Comment by fiveagle** [comment]
I have tried. It doesn't work either.

**Comment by philips77** [comment]
I'll check it on Friday. I'm out of office right now.

**Comment by philips77** [comment]
Hi, 
I tried the sample app without setting the `localElements` and with setting it. Without, I get the `UnknownMessage`, as the delegates for the Configuration Server and Client don't get set. But when I set the local elements to anything, also to an empty array, the config messages are processed normally.

**Comment by philips77** [comment]
@fiveagle Any progress on this? I tried removing this line
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/72e572963aa36113b2a330a79fad918586eb4567/Example/nRFMeshProvision/AppDelegate.swift#L88
from the Sample App and relaunching the app. All Config Message Statuses come as `UnknownMessages`, because the model delegates were `nil`. But when I set the `localElements` to those 2, or even to `[]`, the problem disappeared.

**Comment by fiveagle** [comment]
Hi,
thank You for addressing the issue. Unfortunately I cannot test it because after updating the pod the app crashes on startup while creating the meshNetwork and the provisioner. I'm testing after deleting the old app from the phone.

The stack is:

Error reading state from file
Fatal error: 'try!' expression unexpectedly raised an error: nRFMeshProvision.MeshNetworkError.addressNotAvailable: file /Users/marcodipeco/Development/Altran/p406_ios/P406/Pods/nRFMeshProvision/nRFMeshProvision/Classes/MeshNetworkManager.swift, line 169
2019-10-24 17:12:47.337999+0200 P406[1493:979025] Fatal error: 'try!' expression unexpectedly raised an error: nRFMeshProvision.MeshNetworkError.addressNotAvailable: file /Users/marcodipeco/Development/Altran/p406_ios/P406/Pods/nRFMeshProvision/nRFMeshProvision/Classes/MeshNetworkManager.swift, line 169

Thanks

**Comment by philips77** [comment]
Ech.. looks like i forgot to push one commit :( I'll do this as soon as possible.

**Comment by philips77** [comment]
Ok, I pushed the commits. Also, I'll be merging PRs soon.

**Comment by fiveagle** [comment]
Thanks it works now.
