### ISSUE TITLE
Importing Mesh json doesnt control Generic On Off model

### ISSUE THREAD

**Issue by sunilloharshoreline1** [NordicSemiconductor/IOS-nRF-Mesh-Library#176]
If the mesh json file is imported into the Example project, it doesn't control the Generic On-Off control however the App through which the Mesh is created can control the Generic On-Off model.

**Comment by PM-BubblyNet** [comment]
hi, i think you need to change the provisioner source address, the original / default os 7FFF so something like 6FFF would work I think?

**Comment by philips77** [comment]
Yes, this may be the issue. Reach phone should be set as a new Provisioner with a unique unicast address. Before exporting you should create a new Provisioner in Settings, assign a unique address and ranges, than export and import on another phone. Go to Settings -> Provisioners, click Edit and drag the newly created one to the top to set it as a local one. Reach phone must be a different Provisioner as they must increment their sequence numbers Independently.

**Comment by philips77** [comment]
Did you manage to solve your problem?

**Comment by sunilloharshoreline1** [comment]
I haven't got time to try this. I will post my findings in couple of days. Thanks for your reply.

**Comment by philips77** [comment]
I'm closing the issue due to inactivity. The possible answer has been given above.
