### ISSUE TITLE
The provisioning procedure stops at 37%

### ISSUE THREAD

**Issue by Campou** [NordicSemiconductor/IOS-nRF-Mesh-Library#184]
**Describe the bug**
When using the nRF Mesh App and trying to provision an unprovisioned device, it always stops when the provivisioning procedure is about 37%.

**Expected behavior**
Provisioning is completed successfully.

**Platform details:**
 - Device: [e.g. iPhone6s]
 - OS: [e.g. iOS13.1.3]
 - Library Version (or Commit)[Application version V 1.0.4]

**Comment by philips77** [comment]
Please, migrate to version 2 of the library. I'll release the app on app store today, i hope, and the new library on cocoapods and SPM. Version 1.0.x isn't supported anymore.

**Comment by Campou** [comment]
OK, thanks.
