### ISSUE TITLE
VendorMessage OpCode

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#189]
**Describe the bug**
Hi,
I'm creating a custom VendorMessagge for sending a propertie on my devices. The OpCode I am required to use is 0xC2 but apparently I'm not receiving any response, neither error or success. Reading the log it seems that the NetKey inside the ACK log is different from what I am expecting . 
I'm trying also to test this send on the sample app but I cannot enter "C2" inside the field because the converted value should be minor than 0x3F.

What am I missing?

Thanks

**Logs / Screenshots**
```
▿ RuntimeVendorMessage(opCode: CC6007, parameters: ABCDEF, isSegmented: false, security: Low (32-bit TransMIC))
  - opCode : 13393927
  ▿ parameters : Optional<Data>
    ▿ some : 3 bytes
      - count : 3
      ▿ pointer : 0x000000016eff7b80
        - pointerValue : 6157204352
      ▿ bytes : 3 elements
        - 0 : 171
        - 1 : 205
        - 2 : 239
  - isSegmented : false
  - security : Low (32-bit TransMIC)
```
```
2019-10-30 17:03:16.869476+0100 nRFMeshProvision_Example[4521:2480480] XPC connection interrupted
2019-10-30 17:03:16.879785+0100 nRFMeshProvision_Example[4521:2478179] [Common] _BSMachError: port 28f03; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-10-30 17:03:16.885086+0100 nRFMeshProvision_Example[4521:2480522] [Model] Sending RuntimeVendorMessage(opCode: CC6007, parameters: ABCDEF, isSegmented: false, security: Low (32-bit TransMIC)) from: Element 0 (0x0001), to: 0003
2019-10-30 17:03:16.887020+0100 nRFMeshProvision_Example[4521:2480522] [Access] Sending Access PDU (opcode: 0xCC6007, parameters: 0xABCDEF)
2019-10-30 17:03:16.889400+0100 nRFMeshProvision_Example[4521:2480522] [UpperTransport] Sending Upper Transport PDU (encrypted data: 0x44AE7B461520, transMic: 0xD587BF41) encrypted using key: App Key 1 (index: 0)
2019-10-30 17:03:16.890628+0100 nRFMeshProvision_Example[4521:2480522] [LowerTransport] Sending Access Message (akf: 1, aid: 0x36, szmic: 0, data: 0x44AE7B461520D587BF41)
2019-10-30 17:03:16.902454+0100 nRFMeshProvision_Example[4521:2480522] [Network] Sending Network PDU (ivi: 0, nid: 0x3D, ctl: 0, ttl: 5, seq: 14, src: 0001, dst: 0003, transportPdu: 0x903F9BB1F91D386457EB3D, netMic: 0xC5CF9897) encrypted using Primary Network Key (index: 0)
2019-10-30 17:03:16.904823+0100 nRFMeshProvision_Example[4521:2480522] [Bearer] -> 0x003DCFD0C2F0DA2998ED903F9BB1F91D386457EB3DC5CF9897
```
```
▿ ACK (seqZero: 988, blockAck: 0x0000003F)
  - source : 13
  - destination : 1
  ▿ networkKey : newMeshNetwork1 Network Key (index: 1)
  - opCode : 0
  - isOnBehalfOfLowPowerNode : false
  - sequenceZero : 988
  - blockAck : 63
  ▿ upperTransportPdu : 4 bytes
    - count : 4
    ▿ pointer : 0x000000016dca5ad0
      - pointerValue : 6136945360
    ▿ bytes : 4 elements
      - 0 : 0
      - 1 : 0
      - 2 : 0
      - 3 : 63
  - type : Control Message
```

**Comment by philips77** [comment]
There's a lot that isn't right here.
First of all, don't use `RuntimeVendorMessage` from the sample app. In the sample app the op code was dynamic, provided by the user in UI, that's why it's being used. You should create a struct that extends `StaticVendorMessage` and provide the op code in there as a static parameter, just like any message in the library (in the lib there aren't any static vendor messages, but all config or generic message are static). If you're expecting another message as a status to this one, you have to create second message type for the status as well. Then, you need to create a local model in one of local elements, create a `ModelDelegate` which in `messageTypes` contains this status message op code and type. Only than the status message will be instantiated correctly. Let's say your device has model with ID XXXXYYYY, where XXXX is the server model id and YYYY is your company identifier (or the other way around, i don't remember). Than you should have a corresponding client model with ID XXXX(+1)YYYY.
Secondly, your message is not segmented, so there will be no ack for this message. The one you see must be for some other message.
And lastly, the UI in the sample app for the vendor messages op code adds 0xC0 automatically to your message op code. Just type 2 there, as your op code is in fact 2. 0xC0 is just a bit mask that this is a vendor message. A vendor message may have op codes from 0x00 to 0x3F. The 2 msb are then set to 1, and the 2 following bytes set to the model company identifier.

**Comment by fiveagle** [comment]
Great thanks,
Anyway from the app I see that I can only send a Hex value as Data. I need to send a long string with an EnOcean key. How should I procede?
I also see that it took a while to have a node available after provisioning. How should I get the right moment for starting the sending of the messages safely?

Thanks.

**Comment by philips77** [comment]
You may either just convert the string to hex, or modify the source on your own to accept this string.
Regarding provisioning, it indeed takes some time before the freshly provisioned device will connect and be ready. But when you have already provisioned and configured one, and you provision next, you don't need to disconnect and connect again. Via ADV bearer they're available right away. You may either listen to the bearer state, or repeat sending the message.

**Comment by philips77** [comment]
Hi, can we close this issue now?

**Comment by fiveagle** [comment]
Hi,
I still have some questions.

- When I create and add a `ModelDelegate` to localElements can I assign multiple delegates to the same `sigModelId`?

- In `meshNetworkManager(_ manager: MeshNetworkManager,
                            didReceiveMessage message: MeshMessage,
                            sentFrom source: Address, to destination: Address)`
    can I cast the message as my custom `StaticVendorMessage`?
  
- If not how should use this code: 
   `case let message as UnknownMessage where  (message.opCode & 0xC0FFFF) == (0xC00000 | UInt32(propertyModel!.companyIdentifier!.bigEndian)):`
   to understand which message I have been sending? (Since all my messages have the same opCode)

ThankYou

**Comment by philips77** [comment]
1. You assign one model delegate per model. A delegate can support multiple message op codes, which you declare in `messageTypes`. An example is in the sample app, the `GenericOnOffServerDelegate`.
2. and 3. In order for message to be instantiated as you vendor message, not the `UnknownMessage`, declare a vendor model in the `localElements`, in the model delegate declare you vendor message op code and type, and implement the model behavior (optionally). By your vendor message type I mean your struct, which extends `StaticVendorMessage` and implements message serialization. There's no example in the Sample app, but it should be just like lets say `GenericOnOffSet`, but extend static vendor message, not generic message, and the op code should be 24 bit long and has 2 first bits set to 1 and 2 LSB set to your company id.

**Comment by fiveagle** [comment]
So this is correct. Is'n it?
` let element0 = Element(name: "Primary Element", location: .first, models: [
            Model(sigModelId: 0x0001, delegate: GreenPropertyKeyModelDelegate()),
            Model(sigModelId: 0x0001, delegate: GreenPropertyButtonModelDelegate()),
            Model(sigModelId: 0x0001, delegate: WiredPropertyButtonModelDelegate())
        ])
        `

My `opCode`s are all the same. So I can't assign multiple messages with the same `opCode` to the same `modelDelegate`. Is this correct?

Thanks

**Comment by philips77** [comment]
First of all, I think you are using a vendor model, not a SIG model. You should use this *init* instead:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/dae83c9197a2739c4c1842a4a3d9ddd796d76b50/nRFMeshProvision/Classes/Mesh%20Model/Model.swift#L96
For the `companyId` you should use the identifier from: https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/ (on the right, above the list there is search form). 
For `clientId` you should use the model ID that matches to the model on your device. For example, if your company ID is 0xABCD and you define a vendor model 0x0000 and call it "Property Model Server", on the phone you should define a corresponding client model: 0x0001 with the same company ID, and call it let's say "Property Model Client". You should have one client model per one server model on the device. Each server model should have even model id and client model should have this id+1.
Let's say that you have a single client model that can send 3 type of messages, let's say `GreenPropertyKeySet`, `GreenPropertyButtonSet` and `WiredPropertyButtonSet`, to the server and the server replies with 2 types of messages: `KeyPropertyStatus` and `ButtonPropertyStatus`. You should have the following code:
```swift
let element0 = Element(name: "Primary Element", location: .first, models: [
                          Model(modelId: 0x0001, companyId: 0xABCD delegate: PropertyModelClientDelegate())
])
```
and the delegate should look somewhat like this:
```swift
import Foundation
import nRFMeshProvision

class PropertyModelClientDelegate: ModelDelegate {
    let messageTypes: [UInt32 : MeshMessage.Type]
    let isSubscriptionSupported: Bool = true/false
    
    init() {
        let types: [StaticVendorMessage.Type] = [
            KeyPropertyStatus.self, 
            ButtonPropertyStatus.self
        ]
        messageTypes = types.toMap()
    }
    
    // MARK: - Message handlers
    
    func model(_ model: Model, didReceiveAcknowledgedMessage request: AcknowledgedMeshMessage,
               from source: Address, sentTo destination: MeshAddress) -> MeshMessage {
        // None of your messages in messageTypes is acknowledged, so this method will never be called.
        fatalError("Not possible")
    }
    
    func model(_ model: Model, didReceiveUnacknowledgedMessage message: MeshMessage,
               from source: Address, sentTo destination: MeshAddress) {
        // Not possible?
    }
    
    func model(_ model: Model, didReceiveResponse response: MeshMessage,
               toAcknowledgedMessage request: AcknowledgedMeshMessage,
               from source: Address) {
        // Here you will receive status messages.
        // TODO: Implement.
    }
}
```

**Comment by philips77** [comment]
Also, one op code should be handled only by one model. This is because messages are addressed by element unicast id, not the model id.

**Comment by philips77** [comment]
Hi @fiveagle, have a look at #194 that I've just submitted. Hope it will help you.

**Comment by philips77** [comment]
I'm closing this issue here. If you have any more questions, please create a new one.
