### ISSUE TITLE
can't display two or more provisioned devices 

### ISSUE THREAD

**Issue by YoYo0304** [NordicSemiconductor/IOS-nRF-Mesh-Library#210]
Hello. I am using the example with the version 2.1.0. It seems that the APP can not display two nodes 
after two devices are provisioned. Is there anything I missed?

**Comment by philips77** [comment]
Has the provisioning finished successfully? Did you use unique Unicast Address for each of them? 
You need to provide more information, like screenshots, logs, etc.

**Comment by zhangjinliang1985** [comment]
Yeah. The provisioning finished successfully.
1. The first node's Unicast Address is 0x0001. You can see it on the screenshot below:
![image](https://user-images.githubusercontent.com/10875263/69230950-39888d00-0bc3-11ea-815a-280e26faba3c.png)


2. But after the second node has been provisioned successfully, the first node was disappeared. Only the second node is shown in the app. 
 
![image](https://user-images.githubusercontent.com/10875263/69230912-24136300-0bc3-11ea-9997-d613325b0c1e.png)

**Comment by philips77** [comment]
This is weird. I just repeated what you did and I see 2 devices (+ the provisioner). Can you send us the hex files you are using for both nodes? Can they be flashed onnRF52 DK?

**Comment by zhangjinliang1985** [comment]
yeah. i am using zephyr-based device. i will give you the hex files. There are two hex files. One is the boot hex file and the other is app hex file. You should flash both of them on nRF52 DK.  I have sent you a email. Please check it.

**Comment by zhangjinliang1985** [comment]
Oh. I just remember that the demo app of the version 1.0.2 does not have this problem.

**Comment by zhangjinliang1985** [comment]
The hex files are for the nrf52832 chip.

**Comment by zhangjinliang1985** [comment]
I also have tried the android app of the newest version. It also has this problem.

**Comment by philips77** [comment]
Thank you, I did get the hex files and will check them today.

**Comment by philips77** [comment]
I think the issue is that both your devices advertise with the same UUID, so the app assumes it's the same device and just replaces it. Each device should have a random UUID instead.

**Comment by YoYo0304** [comment]
OK. let me try. thank you

**Comment by philips77** [comment]
Did it work?

**Comment by YoYo0304** [comment]
yeah. Thank you very much
