### ISSUE TITLE
Vendor model companyIdentifier is zero

### ISSUE THREAD

**Issue by codepgq** [NordicSemiconductor/IOS-nRF-Mesh-Library#214]
![image](https://user-images.githubusercontent.com/20208598/69472199-e8a2af80-0de1-11ea-92c6-e42d60750d73.png)

My Vendor model ID is 0x02110000, but after this conversion it becomes 0, it should be 0x0211.

**Comment by philips77** [comment]
I think this is correct. Your company identifier is 0x0211 (Telink Semiconductor Co. Ltd) and model of is 0x0000. There's no company id with number 0x0000. On the other hand, Model IDs usually start from 0 (this depends on the company, of course).

**Comment by philips77** [comment]
Vendor model IDs are defined by 2 values: the company id, defined here: https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/, and 16-bit model id, assigned by the company.
