### ISSUE TITLE
Next Available Unicast Address starting after x offset

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#221]
**Is your feature request related to a problem? Please describe.**
Hi,
I need to keep available the first 100 address for a specific mesh device kind and at the same time keep adding the usual ones assign address greater than 100.

**Describe the solution you'd like**
Is it possible to had an nextAvailableAddress with an offset argument?

**Describe alternatives you've considered**
Right now I am adding 100 if needed but I don't think that it is future proof.

Thanks.

**Comment by philips77** [comment]
Good use case. I'll try to add this method.

**Comment by philips77** [comment]
@fiveagle I applied the changes given by you in #258.
