### ISSUE TITLE
Lighting Model and Sensor model

### ISSUE THREAD

**Issue by Baothien1301** [NordicSemiconductor/IOS-nRF-Mesh-Library#222]
Can you add more lighting model?
 - Lightness (model id: 1300 - 1302)
 - Light CTL (model id: 1303 - 1306)
 - Light HSL (model id: 1307 - 1309)

**Comment by philips77** [comment]
Lightness, Light CTL and Light HSL messages were added in version 2.2.0. If you want to send those messages in your app you have to create a local model that will support them (for example Lightness Client Model), define which message opcodes it supports and implement it, if needed.
have a look how Generic OnOff Client/Server are implemented in the sample app.
