### ISSUE TITLE
Proxy with speaking name

### ISSUE THREAD

**Issue by igathedub** [NordicSemiconductor/IOS-nRF-Mesh-Library#223]
**Is your feature request related to a problem? Please describe.**
When choosing proxy it is unclear to which node they belong, as Node names can be changed.
For example my nodes are (re)named 1 to 5. But proxies all have the same name.

**Describe the solution you'd like**
Somehow correlate proxy name to the renamed node. So in my example above I would see proxies 1 to 5

**Comment by philips77** [comment]
This is not possible, unfortunately. Proxies often advertise only with Network Id, which is not enough to identify them. They may also change Mac address (it's not available on iOS, but even if, it couldn't be used for identification). You may program proxies to advertise their addresses or some random id to distinguish them.
