### ISSUE TITLE
Question: Re-connect to node after provisioning to get comp data.

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/IOS-nRF-Mesh-Library#224]
I was wondering if there is a way to re-connect to a node after provisioning to finish getting comp data and TTL. I tried by keeping track of the peripheral identifier which worked for a little while, but seemed to change recently. I know you can do this in Android, is it possible in iOS?

**Comment by philips77** [comment]
Yes, it's possible. For a short time after provisioning a node is advertising with node identity, which includes its primary address. The sample app displays such nodes together with those advertising Network Id, but i'm your app you could be able to distinguish them and connect to selected one.
