### ISSUE TITLE
Can not set publication address to a unicast addr? 

### ISSUE THREAD

**Issue by YoYo0304** [NordicSemiconductor/IOS-nRF-Mesh-Library#225]
There are a sensor model server  and a sensor client in our bluetooth mesh net. But i can not set the 
publication addr of the sensor model server to the sensor modle client's addr.   
![image](https://user-images.githubusercontent.com/10875263/69842972-72e68a00-12a0-11ea-9fe6-3b323e6ec6e3.png)

**Comment by YoYo0304** [comment]
but when using the android app,  the same configuration is ok

**Comment by philips77** [comment]
The element will appear on the list of it has a compatible model which is bound to selected application key. Make sure that the server is bound to this key before setting publication.

**Comment by YoYo0304** [comment]
yeah. The server has been bound to the app key. 
![image](https://user-images.githubusercontent.com/10875263/69924982-f7c3e480-14e8-11ea-85a0-8b1701bc4c06.png)

**Comment by philips77** [comment]
Och.. then it's a bug in the library. I assumed that all "matching" models (server-client pairs) have IDs differing by 1 (where even is the server and odd is the client), but in this case it's different:
![obraz](https://user-images.githubusercontent.com/6576580/69943908-49b73b00-14e6-11ea-86d8-cc065fbd195a.png)
You will have to modify the source code of the app to make it work. I'll fix it in the upcoming bug-fixing release.

**Comment by YoYo0304** [comment]
OK. thanks
