### ISSUE TITLE
What is Discarding Packets ?

### ISSUE THREAD

**Issue by deverickasih** [NordicSemiconductor/IOS-nRF-Mesh-Library#228]
On occasions, i receive discarding packets and it results in a timeout when i try to bind application keys to elements and also set publish to all nodes for every element. 

What i usually do is after provisioning the node, after composition data and ttl is completed, i immediately bind applicationkeys starting with element at index 1 and wait for the didReceiveMessage delegate (for bindkey process) before setting publish address to all nodes, and then wait for the didReceiveMessage delegate (for publishing process) before binding applicationkeys to element at the next index.. This goes on until the last element has been set applicationkeys and is publishing to all nodes. It is during this process that i get discarding packets.

**Question :**
What is discarding packets, and why does it happen? How do i ensure it does not happen?

Is it a best practice to set a 1 second delay before binding app key and before publishing to all nodes for each element? Or should i leave it be and allow the publishing to all nodes happen right after binding appkey without any form of delay?

**Comment by philips77** [comment]
The packets are discarded in 2 places:
1. When an identical packet is received for a second or more times, it is discarded in Network Layer:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/10acde1cadc78f6ca08082cea8002578495d6491/nRFMeshProvision/Classes/Layers/Network%20Layer/NetworkLayer.swift#L93-L97
2. In Lower Transport Layer when the received packet has sequence number lower or equal to one that was already processed from the originating element:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/10acde1cadc78f6ca08082cea8002578495d6491/nRFMeshProvision/Classes/Layers/Lower%20Transport%20Layer/LowerTransportLayer.swift#L323-L328
This is not an unusual situation. When you have multiple nodes that relay messages, it may happen that you receive the same packet multiple times, each time relayed by different nodes. Each relay node will modify the packet and lower the TTL value (Time To Live), so they are not discarded on the Network Layer using the cache mechanism (1).

I don't think you may do anything about discarding packets. The network operates normally. To increase probability of successful delivery of packets you may increase Network Transmit on the origination node, Relay Count on Relay Nodes or other parameters in your network.
