### ISSUE TITLE
Import and export / IOS and android

### ISSUE THREAD

**Issue by Baothien1301** [NordicSemiconductor/IOS-nRF-Mesh-Library#233]
Hi!
I found an issue:

When i import a json file exported from IOS on android, it is success. But when i import a json file exported from Android on IOS, it is fail. And i read json files export from IOS and Android, i see difference. Json file export from Android have not "group" and when I add "group" and import again, it is success.
I think this issue will be solved soon.

**Comment by philips77** [comment]
Answered here: https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/issues/286
