### ISSUE TITLE
Sharing Scenes

### ISSUE THREAD

**Issue by Baothien1301** [NordicSemiconductor/IOS-nRF-Mesh-Library#241]
I am using sense for my project. And i got a difficult matter when i want to share my senses. Because in json file i don't see anythings about sense. I have to share sense by another way. 
So, i would like to ask you: Do you have any idea for me? Or Do you have a plan about this matter?

**Comment by philips77** [comment]
What do you mean by Sense?

**Comment by Baothien1301** [comment]
I'm so sorry about my mistake. i mean "Scense" not "Sense".
I am using scense for my project. And i got a difficult matter when i want to share my scenses. Because in json file i don't see anythings about scense. I have to share scense by another way.
So, i would like to ask you: Do you have any idea for me? Or Do you have a plan about this matter?

**Comment by philips77** [comment]
Oh, scenes. As they're not implement yet in the sample app, we skipped them from the library as well. They should be in the Json at some point. I'll try to add it in the next release, but I can't promise any date now.

**Comment by Baothien1301** [comment]
Thanks you. You are great!

**Comment by philips77** [comment]
Sharing scenes is now implemented and available in #290. It will be released as version 3.0 (soon on GitHub, then on AppStore when Android version is updated as well).
