### ISSUE TITLE
App stuck on resetting Zephyr node

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/IOS-nRF-Mesh-Library#244]
The app is resetting all devices properly but the alert gets hung up as the app doesn't receive the status from the Zephyr example. I was wondering if you are getting the same behavior.

**Comment by philips77** [comment]
Some devices reset before sending the `NodeResetStatus` message. The app waits for the status message and should time out after ~40 sec. You may click Cancel before. As the status message hasn't been received, but the device got reset, you need to remove the node manually in the node configuration screen.
This is an issue with the zephyr implementation.

**Comment by BubblyNetDev** [comment]
Thanks!
