### ISSUE TITLE
Race Condition?

### ISSUE THREAD

**Issue by kiyoshi-brilliant** [NordicSemiconductor/IOS-nRF-Mesh-Library#246]
**Describe the bug**
While using the library I occasionally get index out of bounds errors in the ProxyFilter.swift on the removeFirst() method call in the following lines:
```swift
            guard buffer.isEmpty else {
                let message = buffer.removeFirst()
                try? manager.send(message)
                return
            }
```

I also occasionally get EXC_BAD_ACCESS errors in the _swift_release_dealloc method on random qos: background threads.

I believe at least the first problem (and possibly the second) to be due to race conditions.

**To Reproduce**
This happens sporadically but what I am usually doing is:
1. Start with MeshConnection disconnected (not connected to any MeshProxies)
2. Search for Unprovisioned node
3. Provision Node
4. Disconnect from Unprovisioned node
5. Start Mesh Connection (Search for 1 Mesh Proxy and connect)
6. Get Composition Data

**Expected behavior**
Expected not to crash.

**Platform details:**
 - Device: iPhone11 Pro
 - OS: iOS12
 - Library Version (or Commit): 2.2.1

**Proposed Solution**
The MeshNetworkManager takes a Dispatch Queue in its constructor but defaults to DispatchQueue.global(qos: background). I believe DispatchQueue.global is concurrent and this problem (at least the first but possibly the second) would be solved by using a serial DispatchQueue. This can be done by a user of the library by passing a different queue, but I think changing the default arg to something like DispatchQueue("MeshNetwork", qos: .background) might be good? Seems simpler than adding synchronization to the buffer array in ProxyFilter at least.

**Comment by philips77** [comment]
My intention was that the lib could work with concurrent queue, so I added synchronization in the `ProxyFilter` type. It will be released in 2.2.2.
