### ISSUE TITLE
Mesh message!

### ISSUE THREAD

**Issue by dqapollo2018** [NordicSemiconductor/IOS-nRF-Mesh-Library#247]
I send a GenericOnOffGet message. And I recieve a GenericOnOffStatus message in function:

```swift
func meshNetworkManager(_ manager: MeshNetworkManager,
                            didReceiveMessage message: MeshMessage,
                            sentFrom source: Address, to destination: Address) 
{
 logwithtag(nil, "Recieved message with Opcode: \(message.opCode)  para:  \(message.parameters.hex)")

  switch message
        {
  case let status as GenericOnOffStatus:
            let targetStatus = status.isOn
            logwithtag(nil, "ON Off recieved \(targetStatus)  \(source.hex)   \(destination.hex)")
 case let status as LightHSLStatus:
            logwithtag(nil, "HSL recieved")
  default:
      break
  }
}
```
But when i send a LightHSLGet message. I recieved a message, and it is not LightHSLStatus message.
And i check message.opCode and message.parameters. They are right:
message.opCode : 0x8278
message.parameters: 0xFF7FFF7FFFFF
I don't know what is wrong.

**Comment by philips77** [comment]
You need to add Light Client model to at least one local element and include this op code in the supported op code nap in there.
