### ISSUE TITLE
Low power node and friend node

### ISSUE THREAD

**Issue by dqapollo2018** [NordicSemiconductor/IOS-nRF-Mesh-Library#251]
Hi!
I have 2 devices.
Device A: I use low power node - example code from SDK. In json file, feature: {proxy:0, friend: 2, relay:0, lowpower: 0}
Device B: I use lightswitch example code from SDK. In json file, feature: {proxy:0, friend: 2, relay:0, lowpower: 2}
I had let them make friend. 
When i connect proxy with Device A, i can bind key, control Device A, but i can not bind key, control Device B.
When i connect proxy with Device B, i can bind key, control both of them.
If i use 2 Device B, there is not issue.
I want to connect proxy with low power node and control another node. What can i do?

**Comment by philips77** [comment]
I don't know this is possible. After A is low power node and may be active in short period of time. 
Please, ask your question on [DevZone](devzone.nordicsemi.com), our Support Team is more qualified to answer you, and this is not an issue with the mesh library.
