### ISSUE TITLE
When iPhone loses Bluetooth connection, it loses all abilities to send messages to the network.

### ISSUE THREAD

**Issue by PhilippeRivard** [NordicSemiconductor/IOS-nRF-Mesh-Library#254]
**Describe the bug**
When iPhone loses Bluetooth connection, it loses all abilities to send messages to the network (this is on the example app).

**To Reproduce**
1. Provision a device, set it as generic level server for example and subscribe to a group.
2. Set provisioner (your iPhone) as generic level client and subscribe to the same group as the one mentioned in step 1.
3. Control the group using your iPhone and notice that everything works great and the light is changing brightness when iPhone clicks "+" and "-".
4. Disconnect Bluetooth from iPhone.
5. Try to control that group again by clicking "+" and "-" with your iPhone.
6. Light does not react to iPhone's commands

**Expected behavior**
Light should react to "+" and "-" clicks from iPhone.

**Platform details:**
 - Library Version (or Commit)

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster

**Comment by philips77** [comment]
Hello, sorry for coming so late to you. I was busy with other tasks.
What is the issue that you observe? You disconnect from the Proxy Node, so you can't control the network. Neither iOS nor Android can send Mesh messages over ADV bearer at the moment (API limitations), so GATT Bearer needs to be used. This require working Bluetooth LE connection to the Proxy Node.
