### ISSUE TITLE
Unnecessary code?

### ISSUE THREAD

**Issue by horsejockey** [NordicSemiconductor/IOS-nRF-Mesh-Library#255]
I apologize as this may be more of a question than a bug. I am just getting familiar with bluetooth mesh protocol and this is my first time implementing it in an iOS project.  I mainly want to make sure I'm not misunderstanding something which is the likely case.  Here is the question:

Is this code necessary?

```
        // Unless a GATT Bearer is used, the Network PDUs should be sent multiple times
        // if Network Transmit has been set for the local Provisioner's Node.
        if case .networkPdu = type, !(transmitter is GattBearer),
            let networkTransmit = meshNetwork.localProvisioner?.node?.networkTransmit,
            networkTransmit.count > 1 {
            var count = networkTransmit.count
            BackgroundTimer.scheduledTimer(withTimeInterval: networkTransmit.timeInterval, repeats: true) { timer in
                try? self.networkManager.transmitter?.send(networkPdu.pdu, ofType: type)
                count -= 1
                if count == 0 {
                    timer.invalidate()
                }
            }
        }
```

[Link to file in repo](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/45e12224e8b5f2d45659e99dddda966b1ba17789/nRFMeshProvision/Classes/Layers/Network%20Layer/NetworkLayer.swift#L175) 

From what I understand iOS has the limitation that you always must communicate through a GATT Bearer.

**Comment by philips77** [comment]
Yes, but assuming one day iOS would allow sending custom advertising packets, this is already ready. Until then it will never go inside this if. Perhaps it will have to be modified for other bearers, if they pop up. Until then this is noop which reminds about Network Transmit.
