### ISSUE TITLE
Composition Data Get

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/IOS-nRF-Mesh-Library#264]
When getting the Composition Data for a node the nodes features are either set to notSupported or notEnabled when read in from the data. Even if the proxy for example is enabled. Is this expected behavior?

**Comment by philips77** [comment]
Well... In the Composition Data the values should be Supported and Not Supported. Whether they are enabled or not you need to go to Configuration Server model and read the values there. I'll look at the API, perhaps it needs to be changed in this aspect.
