### ISSUE TITLE
Global TTL settings

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#276]
Hi,
we have the necessity to set a specific TTL value for all the proxy messages. 
I've noticed that I can send a TTL value to each node but I was wondering if it is possible to to this globally with some settings on the MeshNetwork communications layers mainly to solve the potential issue to update all the already provisioned nodes with the new TTL in a future update.

Thanks.

**Comment by philips77** [comment]
No. Setting TTL is a confirmation message and needs to be encrypted with device key, therefore sent to each node separately.
