### ISSUE TITLE
hops

### ISSUE THREAD

**Issue by black1997** [NordicSemiconductor/IOS-nRF-Mesh-Library#280]
send Vendor message and receive respond，how to get Through several nodes for this message

**Comment by philips77** [comment]
If *TTL* of the message and response sent is high enough, and there are enough nodes with *Relay feature* enabled on the way, and perhaps *Network Transmit* value on the Relays is set to more than 1 to increase change of message being received you should be able to receive status message after some time. This library also repeats the acknowledged messages had the response not been received in configured time before timing out.
