### ISSUE TITLE
Can it be used for projects developed in Objective-C language？

### ISSUE THREAD

**Issue by Jshto** [NordicSemiconductor/IOS-nRF-Mesh-Library#281]
Can it be used for projects developed in Objective-C language, mixed development, and can Objective-C language projects use the functions of this framework?

**Comment by philips77** [comment]
Not really. This library, on contrary to our DFU library, is using some swift-only types, like `OptionSet`. We have never tried importing this library to Objective-C project and I don't know it can go smoothly. For example, provisioning requires setting `OobInformation` which is an `OptionSet`: https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/master/nRFMeshProvision/Classes/Provisioning/Oob.swift
If possible, you may try and share the result here.
