### ISSUE TITLE
Firmware for Heartbeat and (future) Scenes

### ISSUE THREAD

**Issue by igathedub** [NordicSemiconductor/IOS-nRF-Mesh-Library#288]
Hello Aleksander,

i've seen you merged Heartbeat and are going to implement Scenes (#201 ).
On what firmware/hardware would it run?

Thank you in advance
Igor

**Comment by philips77** [comment]
Hi, 
I was testing heartbeats against nRF Mesh SDK from Nordic, version 4.2. The team is working on implementing Scenes models in the next release. In will run in all supported nrf5 chips. Please, consult the documentation for details.
The nRF Connect SDK based mesh impl also should get Scenes at some point, but I don't know any details.
