### ISSUE TITLE
OpenSSL-Universal update

### ISSUE THREAD

**Issue by codewpf** [NordicSemiconductor/IOS-nRF-Mesh-Library#298]
There is an issue in OpenSSL-Universal 1.0.2.19 which has been solved in 1.0.2.20. [issue solved](https://github.com/facebook/react-native/issues/28824) 

Please update the dependency to 1.0.2.20
Thank you.

**Comment by philips77** [comment]
Hi, I'm back at work and will look into that at some point.

**Comment by philips77** [comment]
Hi,
I migrated the library to [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) instead of OpenSSL. Check out #322.

**Comment by codewpf** [comment]
Great, thank you.
