### ISSUE TITLE
Time Set

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#320]
Hi,
I'm doing some preliminary research on a new feature I need to implement. We need to send a Time Set Message (opCode 0x5C). 
I see the library only includes `GenericDefaultTransitionTimeSet` but it doesn't look quite the same since the fields are different.

From the SIG Mesh Model specification:
![image](https://user-images.githubusercontent.com/1208880/107029583-89934580-67af-11eb-8464-ff4e5fcaccad.png)

How can we overcome this? Is this message implemented on version 3?

Thanks a lot.

**Comment by philips77** [comment]
Hello,
There is currently no TimeSet message implemented. I'll be releasing 3.0 today, so there's no time to add it now, but we plan having 3.1 very soon afterwards.
If you implement it, consider creating a PR so we will gladly accept it!

**Comment by fiveagle** [comment]
> If you implement it, consider creating a PR so we will gladly accept it!
Undoubtedly it's something we can consider after updating to 3.0 but we also need to keep iOS and Android in sync. 
Eventually I'll ask questions on this thread.

**Comment by philips77** [comment]
Let me just reference #423 here, as Time Set was mentioned there.

**Comment by philips77** [comment]
Closed with #443, long time ago.
