### ISSUE TITLE
Nrf mesh cannot detect my light device

### ISSUE THREAD

**Issue by mesha227** [NordicSemiconductor/IOS-nRF-Mesh-Library#361]
I am unable to detect the light bulb through nrf mesh even after using different phone models, iPhone and android. I am currently using nrf mesh version 3.1.4 and nrf sdk mesh version 5.0.0
I could still connect to it via nrf connect.

**Comment by philips77** [comment]
Are you sure that your light bulb is unprovisioned and advertising as such?
Could you tell how do you see it in nRF Connect?

**Comment by mesha227** [comment]
this is what i see on the nRF connect
![IMG_0035](https://user-images.githubusercontent.com/86702674/124407344-421cdf80-dd76-11eb-8510-4b637e3008a2.jpg)

**Comment by philips77** [comment]
Those are all custom services and characteristics, with nothing in common with Bluetooth mesh. Seems like your device doesn't support mesh, so it will not work with nRF Mesh.
