### ISSUE TITLE
AcknowledgedStaticVendorMessage clarification

### ISSUE THREAD

**Issue by Luzo** [NordicSemiconductor/IOS-nRF-Mesh-Library#371]
**Use case description**
Hi, I am trying to send a message to a node in my mesh. Node provisioning is complete, node is configured via `ConfigMessages`. Application key is bound to models of node with given address(Target node) with `ConfigModelAppBind`.

This all goes through with no problem.

I have created custom subclass of `AcknowledgedStaticVendorMessage`, let's call it `SubclassMessage`. The message sets some light levels. OpCode should be correct - 0xC2E502 (code 0xc1 and vendor: 02e5).

on Android they send it as easy as this:
```java
  meshManagerApi.createMeshPdu(
          element.getElementAddress(),
          new VendorModelMessageAcked(
            meshManagerApi.getMeshNetwork().getAppKey(0),
            0x02e51414,
            0x02e5,
            0xc1,
            bb.array()
          )
        );
```
but there is nothing as easy as that on iOS
 
And now the problem or the question of correct approach arises. I tried 2 different approaches of sending messages. None of them work as I would expect.

**First approach**
I do not create any local model, I just add element from the network to local elements:
` MeshNetworkManager.instance.localElements.append(element)`
I am trying to send my `SubclassMessage` through api of meshNetwork

`MeshNetworkManager.instance.send(SubclassMessage(data: someData), to: node)`

**Result**
Message goes through, but since it has no delegate the response is `UnknownMessage`. Which is correct by the documentation provided.

**Questions**
Is it possible to somehow set the delegate of non local node, or am I supposed to somehow cast the `UnknownMessage` to my message? Or is it incorrect approach.

**Second approach**
I create local model like this:
```swift
 if node.elements.contains(modelWithId: 0x02e51414) {
        if let model = $0.model(withModelId: 0x02e51414), let element = model.parentElement {
          let localModel = Model(
            vendorModelId: 0x1414,
            companyId: model.companyIdentifier!,
            delegate: delegate
          )
          let localElement = Element(name: "Primary Element", location: .first, models: [localModel])
          MeshNetworkManager.instance.localElements.append(localElement)
          meshNetworkDidChange()
          self.delegate.messageData = data
       }
}
```
but the message did not go through since it is missing publish, so I tried to add publish functionality to node:
```swift
bluetoothMeshNetworkService.setPublishing(for: localModel, toAddress: node.unicastAddress) { result in
            switch result {
            case .success:
              DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
                self.delegate.messageData = data
              }
            case .failure(let error):
              Logger.log(message: "\(error)", level: .error)
            }
```
setPublishing looks like this:
```swift
  func setPublishing(for model: Model, toAddress: Address, configurationCompletion: @escaping (Result<Void, Error>) -> Void) {
    guard let node = node, let applicationKey = node.applicationKeys.first else { return }

    self.configurationCompletion = configurationCompletion

    let publish = Publish(
      to: MeshAddress(toAddress),
      using: applicationKey,
      usingFriendshipMaterial: false,
      ttl: node.defaultTTL!,
      period: Publish.Period(steps: 1, resolution: StepResolution.seconds),
      retransmit: Publish.Retransmit(
        publishRetransmitCount: 3,
        intervalSteps: 1
      )
    )

    let message: ConfigMessage =
      ConfigModelPublicationSet(publish, to: model)!

    do {
      Logger.log(message: "ConfigModelPublicationSet send:", level: .info)
      try MeshNetworkManager.instance.send(message, to: node)
    } catch {
      Logger.log(message: "ConfigModelPublicationSet send failure: \(error.localizedDescription)", level: .error)
      configurationCompletion(.failure(BluetoothMeshNetworkServiceError.configurationFailed))
    }
  }
```
`configurationCompletion` is called upon receiving status message

**Result**
`ConfigModelPublicationSet` fails with incorrect address. I tried to add there `unicastAdress` of the remote node or the element itself with no luck. I also tried local model address.

**Questions**
Which address should be set to this? Is it really necessary to set Publish functionality or am I doing it all wrong?

Thank you for the clarification, I could not find my answers in documentation, or the other issues.

**Comment by philips77** [comment]
Hello, and thank you for asking your question.

> Is it possible to somehow set the delegate of non local node, or am I supposed to somehow cast the UnknownMessage to my message? Or is it incorrect approach.

First approach is incorrect. To get status parsed you need a local model that supports it.

I'm the second approach it looks like you're adding the local element only is a remote node has a specific model. That is not necessary and I don't know how may that work. As you support those status messages in your app, by definition you have this model anyway, so just add it just after loading the network manager.

With the model set up you may set publication on it, but you need to bind the correct app key first. With all key blind you'll be getting the status messages in your model delegate, with publication set up you'll also be able to use `publish` method in it. But you may also just use the first approach now and just send messages using `send`. They'll be parsed correctly now, as the model binds a message type with an op code.

**Comment by philips77** [comment]
> I do not create any local model, I just add element from the network to local elements:

You need to create local element with supported models.

**Comment by philips77** [comment]
Hello, did you manage to solve your issue?

**Comment by Luzo** [comment]
Thank you, it has been resolved. I have used local element with models, I am sending message directly. To bypass mapping as unknown messages delegate is set(at least from what I recall my colleague said).

**Comment by philips77** [comment]
Yes, you should have a delegate that would do the mapping. You don't have to use it the way it was designed to be, so all the methods inside can be empty, with just the mapping returning your message type. Then you may send messages directly.

> Note: Should you ever wanted to use `ModelDelegate`'s methods, remember that for them to be called, the local model needs to be bound with an Application Key that the messages are sent with.
