### ISSUE TITLE
Questions about connecting to multiple devices

### ISSUE THREAD

**Issue by okappi0258** [NordicSemiconductor/IOS-nRF-Mesh-Library#374]
I want to connect multiple peripherals to one ipad. However, only one peripheral is connected. The messages are sent to the group address, so they reach all the peripherals, but when the communication between the ipad and the connected peripheral is disconnected, it starts connecting to another peripheral, and I cannot receive messages while it is connected. Is it possible to have multiple peripherals connected to one central?

**Comment by philips77** [comment]
Yes, it's possible. The nRF Mesh app has `NetworkConnection` class that allows that, but it's fixed to 1. But in principle, an iphone or Android device should easily connect to at least 6 devices simultaneously.
