### ISSUE TITLE
Share network to other iphone

### ISSUE THREAD

**Issue by songhongkang** [NordicSemiconductor/IOS-nRF-Mesh-Library#382]
hi philips77, Ask your question

I want to implement a sharing function，What should I do?

Shared file path   `Documents/MeshNetwork.json` 、  `Library/Preferences/meshUUID.plist`.

Shared the above two files，Still out of control.

**Comment by philips77** [comment]
Sharing the mesh network configuration is showed in the sample app. You need to call `export()` method and that will give you the json file. You may do whatever you want with it.
