### ISSUE TITLE
nrf-Mesh mobile-application should support PB-AD Provisioning Bearer

### ISSUE THREAD

**Issue by niravagrawal552** [NordicSemiconductor/IOS-nRF-Mesh-Library#383]
I am working with Bluez5.62 on arm based board where I need to join my device on nrf-mesh mobile application. But I could see that Bluez start advertising unprovisioned mesh beacon on hcidump but could not see any beacon on nrf-mesh application.

I assume the issue could be related with provisioning bearer. Bluez mesh service supports PB-AD bearer and nrf-mesh supports PB-GATT bearer. 

I would be very grateful if you can provide any roadmap plan for adding PB-AD bearer support or some insights on "How to add PB-AD bearer support on nrf-mesh mobile app" ?

Seeking your assistance as this understanding is very important for us. 

Regards,
Nirav Agrawal

**Comment by philips77** [comment]
Hello,
We would really like to have PB-ADV and in general ADV bearer, but that is not possible on Android or iOS, unfortunately. That is, actually, the main reason behind inventing GATT bearers in the first place. Android API allows to scan for ADV bearer messages, as there is `getRawData()` method, that could be used for that, but there is no option to sent a custom AD tlv in advertising data, so it cannot participate in exchanging messages using just advertising. On iOS it's even worse, as they can only advertise with Service UUID and only with the app in foreground, while scanning is limited to some standard AD types, like Service Data or Manufacturer Data. So it's not possible to advertise or even scan.

You'll need to add GATT bearer and PB-GATT to your project, which is much easier than convincing Google and Apple to modify their APIs (which would only allow updated devices to use it).
