### ISSUE TITLE
How could i cancel a retry stragety for

### ISSUE THREAD

**Issue by Wtoto** [NordicSemiconductor/IOS-nRF-Mesh-Library#385]
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/50c596cc621b0b82bd9f071246a5004f483d8401/nRFMeshProvision/Classes/Layers/Access%20Layer/AccessLayer.swift#L239-L242

Can i cancel it and use my own application timer?

**Comment by Wtoto** [comment]
// Set timers for the acknowledged messages.
        if let _ = message as? AcknowledgedConfigMessage {
            createReliableContext(for: pdu, sentFrom: element, withTtl: initialTtl, using: keySet)
        }


can i cancel it and use my own application timer？

**Comment by philips77** [comment]
You may use unacknowledged messages, those have no timeout and retry procedure. But why do you want your own timer? You may control the timer duration, retry interval, etc, using parameters in `MeshNetworkManager`:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/50c596cc621b0b82bd9f071246a5004f483d8401/nRFMeshProvision/Classes/MeshNetworkManager.swift#L70-L113

**Comment by philips77** [comment]
The 30 sec timer is actually due to the Bluetooth Mesh Profile 1.0.1 specification. It explicitly states, that the timeout should be at least 30 seconds.

However, rules are set to be be broken, right?

**Comment by philips77** [comment]
Btw, did you manage to solve your issue? I'm considering lowering the 30 sec constraint, leaving it only in the documentation.

**Comment by Wtoto** [comment]
> 30 seconds

**Comment by Wtoto** [comment]
> Btw, did you manage to solve your issue? I'm considering lowering the 30 sec constraint, leaving it only in the documentation.

You are right.   Bluetooth Mesh Profile 1.0.1 does specify a minimum time. 
However, the 30 sec is too long for our PM.
I used the MessageHandle to cancel the message, before i resend the message. 
Thanks.
