### ISSUE TITLE
Dependency "IOS-nRF-Mesh-Library" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by Ong9uJ** [NordicSemiconductor/IOS-nRF-Mesh-Library#396]
carthage version: `0.38.0`
xcodebuild -version: `Xcode 13.2.1` `Build version 13C100`

Cartfile
`github "NordicSemiconductor/IOS-nRF-Mesh-Library"`

Using command
`carthage update --platform iOS`

Carthage Output
`Dependency "IOS-nRF-Mesh-Library" has no shared framework schemes for any of the platforms: iOS`

Expected
Carthage should build

Actual
Carthage did not build

**Comment by philips77** [comment]
Did you make it work? What was the issue?

**Comment by Ong9uJ** [comment]
I cannot solve this problem...

**Comment by philips77** [comment]
This might have been fixed long time ago. Closing for now.
