### ISSUE TITLE
Which DevicePropertyCharacteristic we can use for sensor Property CO2?

### ISSUE THREAD

**Issue by bhautikVolansys** [NordicSemiconductor/IOS-nRF-Mesh-Library#425]
Hello Team, 
Greeting!

Can you help me out to suggest DevicePropertyCharacteristic for Sensor property CO2?
As a we are using Nordic Kit's Temperature, Humidity, Par & CO2 property for setSensorCadence in our project.
Which DevicePropertyCharacteristic we can use for sensor Property CO2? 
Notes:- In our exist code we have specific DevicePropertyCharacteristic as like given below list:
   - For Temperature we have temperature(Decimal?)
   - For Humidity we have humidity(Decimal?)
   - For Par we have illuminance(Decimal?)
   - For CO2 can you help me out to find DevicePropertyCharacteristic ?

**Comment by bhautikVolansys** [comment]
@philips77 , Can you please take a look into this?

**Comment by philips77** [comment]
Here is the spec: https://www.bluetooth.com/specifications/specs/mesh-device-properties-2/

**Comment by philips77** [comment]
Have a look at:

> 3.5.12 Present Ambient Carbon Dioxide Concentration device property
This property represents present ambient carbon dioxide concentration measured by a CO2 sensor.
Characteristic: CO2 Concentration

**Comment by philips77** [comment]
Characteristics are specified here: https://www.bluetooth.com/specifications/specs/gatt-specification-supplement-6/

**Comment by philips77** [comment]
Chapter 3.45 is what you're looking for.

**Comment by philips77** [comment]
You're looking for this property:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/00ef0cc1ebaf054348e8a0ab2fa351dd4b5fcef1/nRFMeshProvision/Classes/Mesh%20Messages/DeviceProperty.swift#L159

**Comment by philips77** [comment]
Indeed, it's missing here:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/00ef0cc1ebaf054348e8a0ab2fa351dd4b5fcef1/nRFMeshProvision/Classes/Mesh%20Messages/DeviceProperty.swift#L933-L942
and somewhere here:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/00ef0cc1ebaf054348e8a0ab2fa351dd4b5fcef1/nRFMeshProvision/Classes/Mesh%20Messages/DeviceProperty.swift#L1090-L1092

**Comment by philips77** [comment]
I can add it tomorrow, i think.

**Comment by bhautikVolansys** [comment]
> You're looking for this property:
> 
> https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/00ef0cc1ebaf054348e8a0ab2fa351dd4b5fcef1/nRFMeshProvision/Classes/Mesh%20Messages/DeviceProperty.swift#L159

Yes @philips77, but in DevicePropertyCharacteristic

**Comment by bhautikVolansys** [comment]
> I can add it tomorrow, I think.

Thank you @philips77, this will help me to implement the sensorCadence feature for CO2.

**Comment by philips77** [comment]
Merged. The next version is coming in few days.

**Comment by philips77** [comment]
I forgot about few things...
