### ISSUE TITLE
How many devices can be kept both using GATT-bearer at the same time ?

### ISSUE THREAD

**Issue by wenjiu1111** [NordicSemiconductor/IOS-nRF-Mesh-Library#432]
Take a look of this senario below:

1. One device (A) powered by battery.
2. Another device (B) powered by constant supply.
3. I need to keep connections(GATT-bearer) with these two devices onto my phone for doing some configurations, and most important, **keeping a low power state for battery-powered device by disabling mesh-relay and turning off long-time-scanning**.

My question: **Is that OK to keep two or more devices  using (MESH) GATT-bearer with my phone (using the lastest library) at the same time?**

**Comment by philips77** [comment]
Yes, the connections are independent from the mesh library, You may have multiple GATT bearers at the same time, as this is supported by iOS. Just remember which one to use to send data (you may use all, as the other nodes may just ignore messages not targeting them).
