### ISSUE TITLE
Facing the issue of Discarding packets because of sequence.

### ISSUE THREAD

**Issue by bhautikVolansys** [NordicSemiconductor/IOS-nRF-Mesh-Library#439]
Hello Team, 

I am using the latest code and facing the issue of Discarding packets because of sequence.

Steps
 I have provisioned the node and then exported the database. I have imported that database and the issue come on every command.

```
Network PDU (ivi: 0, nid: 0x7E, ctl: 0, ttl: 7, seq: 0, src: 0022, dst: C000, transportPdu: 0x46F5B91CE83484F23CFD9D80, netMic: 0xBAF630CA) received
Discarding packet (seqAuth: 0, expected > 77)
```

@philips77 Can you take a look into this?

I have checked this [thread](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/issues/300) also.

Thank You

**Comment by bhautikVolansys** [comment]
@philips77 Can you take a look into this?

**Comment by philips77** [comment]
Hi, I'll have a look at it. I suppose one of our engineers also reported similar observation.
The thing is, I'm on vacation until end of August, so this has to wait. Sorry for that.

Questions: what NCS version are you using? Or nRF5 SDK for mesh?
If you repeat the message, is the `seq` in received message is always 0?
If you resend the message, does the `seq` increase?

**Comment by bhautikVolansys** [comment]
Answers:
1. I am using the latest version of NRF SDK for mesh.
2. After importing the database facing this issue for each command.

**Comment by philips77** [comment]
But.. the logs you provided show that the *incoming* message has `seq` equal to 0, while the library expected greater than 77.
Either your device sends `seq` = 0, or the library fails to decode it. That would be super weird.

Does it work for you before exporting and importing?

I'm on vacations until end of July, so can't debug now, but I'll have a look when I'm back at the office.

**Comment by bhautikVolansys** [comment]
@philips77 Yes, We are facing issues after Exporting and Importing.

**Comment by philips77** [comment]
I'm be able to resume working on mesh next week, I hope.

**Comment by philips77** [comment]
Hi, sorry for 1 year delay. Have you been able to solve the issue?
I did resume working on the library in January, but completely forgot about your issue. Sorry about that.

**Comment by philips77** [comment]
One year passed. Now it seems like it's an easy one to solve. The library remembers last SEQ for outgoing packets for each Unicast Address the local Provisioner is using.
However, when you export and import the network to another device, it will start sending with SEQ = 0, as SEQ is not being exported. If you want to use the same address on the new device as was used on the old one, you'll have to wait until the SEQ number reaches value higher than the one used on the previous device. This is for sure not the intended behavior.

Instead, you should create a new provisioner before exporting, assign a new unicast address to it, and export the configuration with that new provisioner (as a single provisioner, or with others). Then, upon import, select the proper one to be used by the new device. As the Unicast Address will be unique and new, other devices will not reject the messages (unless they reach limit of their Reply Protection List).
