### ISSUE TITLE
SecKeyGeneratePair is deprecated in iOS 15 and should be replaced with SecKeyCreateRandomKey

### ISSUE THREAD

**Issue by justinmeiners** [NordicSemiconductor/IOS-nRF-Mesh-Library#447]
**Describe the bug**
Apple has deprecated `SecKeyGeneratedPair`. This is used in `Crypto/Crypto.swift`.

The replacement is called `SecKeyCreateRandomKey` and it is fairly easy to make a replacement. The replacement was first included in iOS 10.0+.

**Expected behavior**

**Platform details:**
 - Device: iOS devices.
 - OS: iOS 15.0+
 - Library Version: This is in the current main and has been there since at least late 2.x versions.

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster

See https://developer.apple.com/documentation/security/1395339-seckeygeneratepair.
and https://developer.apple.com/documentation/security/1823694-seckeycreaterandomkey.

**Comment by philips77** [comment]
Thank you! I'll fix it when I finally have time to get back to mesh!

**Comment by philips77** [comment]
It took some time, but the issue is fixed. Thanks again for pointing it out.
