### ISSUE TITLE
SPM Package file has incorrect CryptoSwift version (v1.3.2+)

### ISSUE THREAD

**Issue by eanderlind** [NordicSemiconductor/IOS-nRF-Mesh-Library#455]
v1.3.2+: The CryptoSwift version in Package.swift 1.3.8 has not been updated to align with .podspec 1.5.1
Cartfile similarly appears out of date.

It would also be useful if https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/main/Documentation/SETTING_UP.md could be updated, since it doesn't appear to reflect how project is configured:
- the project currently bundles the Pods (in Example/Pods/*) so appears don't need to additionally download them as packages
- if set up a project as an "out-of-tree" development (nRFMeshProvision is a sibling repo to the one where development occurs) there is a 4th pkg mgmt option, where can use Xcode built-in SPM support by following 
https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app
This is much easier than trying to follow SPM cmdline instructions. I am however not sure which CryptoSwift location is 
used (and how to view this) if one thereafter adds nRFMeshProvision as a local package per 
https://developer.apple.com/documentation/xcode/editing-a-package-dependency-as-a-local-package

**Comment by philips77** [comment]
Thanks for pointing that out. I'll fix it when I have some time to resume work on the library, hopefully soon.

**Comment by philips77** [comment]
Fixed in #488.
