### ISSUE TITLE
Show nodes length and searching for node

### ISSUE THREAD

**Issue by Hung6129** [NordicSemiconductor/IOS-nRF-Mesh-Library#473]
Hi @philips77 
I want to add a search bar for searching the node when the list is up to 100 or 200 node
Search bar can use name or unicast address to filter

And showing the list of nodes length on top on the network tab

It's look like this

![image](https://user-images.githubusercontent.com/73824851/219262810-43944da3-89e2-4c9c-8a02-2466c0cd0f51.png)

Can you help me do the searching one my team really need this feature
Or you can give me some document or a way to do it that could also help me a lot

I kinda new to swift, so hope you can check it out
Thanks you

**Comment by philips77** [comment]
That's a good idea. I'll try to implement it, but can't promise any date.

**Comment by philips77** [comment]
Sure! Thanks! We like PRs.

**Comment by philips77** [comment]
The search bar was added with #493.
