### ISSUE TITLE
Strong reference cycle problem between MeshNetworkManager and NetworkManager

### ISSUE THREAD

**Issue by Ong9uJ** [NordicSemiconductor/IOS-nRF-Mesh-Library#476]
`MeshNetworkManager` does not release from memory because of strong reference cycle.

If i create multiple MeshNetworkManager, none of them are released from memory.

You might need to change the reference between NetworkManager and MeshNetworkManager to a weak reference or another alternative.

**Comment by philips77** [comment]
Thank you for creating the issue. I'll look into it soon.

**Comment by philips77** [comment]
In #503 a `MeshNetwrokManager.clear()` methods was added, which sets the `networkManager` to `nil`, effectively breaking the cycle. This is a simple workaround for now. The proper fix removing the reference cycle will come shortly.

**Comment by Ong9uJ** [comment]
Thanks very much!!!!

**Comment by philips77** [comment]
Hi, could you check if the PR fixes the issue? I tried with nRF Mesh app and at least it doesn't break anything.

**Comment by Ong9uJ** [comment]
It fixies my problem without any breaking. thank you!!
