### ISSUE TITLE
Update Network and Application key at start of KeyUpdate

### ISSUE THREAD

**Issue by eanderlind** [NordicSemiconductor/IOS-nRF-Mesh-Library#477]
Is there a way for application to create updates of NetworkKey and ApplicationKey for use in KeyUpdate procedure?
The api in 
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/Mesh%20API/MeshNetwork%2BKeys.swift#L74

recreates a key at same index, while we instead want to invoke the (internal access) didSet  on the  existing key. 
The same api also limits binding to the first Netkey, however it looks like once we have an Appkey we can rebind it using
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/Mesh%20API/ApplicationKey%2BNetworkKey.swift#L40

Hopefully just didn't find correct api.

**Comment by philips77** [comment]
Hi,
Yes, it is possible. For that you have to send [`ConfigNetKeyUpdate`](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/main/nRFMeshProvision/Classes/Mesh%20Messages/Foundation/Configuration/ConfigNetKeyUpdate.swift) or [`ConfigAppKeyUpdate`](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/main/nRFMeshProvision/Classes/Mesh%20Messages/Foundation/Configuration/ConfigAppKeyUpdate.swift) message to [local Node](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/MeshNetworkManager.swift#L643, just like to any other Node.

The message will be handled here:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/Layers/Foundation%20Layer/ConfigurationServerHandler.swift#L139-L145
Setting the key in line 141 does the following:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/Mesh%20Model/NetworkKey.swift#L94-L104
The `update(networkKeyWithIndex` sets the `updated` flag in the Node's key list:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/Mesh%20Model/Node.swift#L748-L756

**Comment by philips77** [comment]
You may find some info here: https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/pull/314

**Comment by eanderlind** [comment]
Thanks - that explains the 2nd half of the process. The remaining part is how to instantiate the two messages with the new key. Looks like only way is to generate a newkey bytestring and then hand craft a msg using the ConfigNetKeyUpdate(parameters:Data) initializer.
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/78b532d500adecfd8fe624497217cfffb39f8c45/nRFMeshProvision/Classes/Mesh%20Messages/Foundation/Configuration/ConfigNetKeyUpdate.swift#L50

Not intuitive, but we will try it out... Thanks. Closing the issue since there is a workaround.

**Comment by philips77** [comment]
Great that you pointed it out. That needs improvement. I'll fix it in the next (big!) release.
