### ISSUE TITLE
Re-adding the same device (same UUID) ends up with it being provisioned but not saved

### ISSUE THREAD

**Issue by philips77** [NordicSemiconductor/IOS-nRF-Mesh-Library#479]
I have a device A advertising a UUID X. I provision it. Then I erase the memory and reprovision it without first removing the old instance from the app.
The provisioning succeeds (the new device gets all the keys, etc), but saving the new instance in the library fails due to the same UUID already existing. I can't reset the device as the lib lost the Device key.

The UUID check should be done BEFORE provisioning, not after.

**Comment by Hung6129** [comment]
In my opinion
I think when this happen
We stop the provision process and show a pop up to tell user to remove that node manually
Or we detect it and remove it then we start the provision process

**Comment by philips77** [comment]
The popup should show up before provisioning, so user can remove it manually.

**Comment by philips77** [comment]
This was fixed by #512.
