### ISSUE TITLE
Remove hard dependency on CryptoSwift 1.3.8

### ISSUE THREAD

**Issue by bspinner** [NordicSemiconductor/IOS-nRF-Mesh-Library#482]
**Is your feature request related to a problem? Please describe.**

We get build warnings and are concerned about security issues due to having to use an old version of CryptoSwift.

**Describe the solution you'd like**

Reference CryptoSwift with `upToNextMajor` instead of `upToNextMinor` in `Package.swift`.

**Describe alternatives you've considered**

Upgrading CryptoSwift by requiring a newer version in our project. But that conflicts with this library's dependency on 1.3.x.

**Additional context**

https://github.com/krzyzanowskim/CryptoSwift/blob/main/CHANGELOG

As of writing, up to date version is 1.7.0.

**Comment by philips77** [comment]
Fixed by #488.
