### ISSUE TITLE
App crash after clicking on the sensor server

### ISSUE THREAD

**Issue by Hung6129** [NordicSemiconductor/IOS-nRF-Mesh-Library#497]
i'm using the app that i clone using the latest update code, its crash after i try to view the model Sensor Server

![ezgif-1-dca003d2d9](https://user-images.githubusercontent.com/73824851/237030446-c22eb7a4-88da-4d99-be51-cef20a1cf3ee.gif)

But when i use the nRF Mesh on App Store it still work fine and i can config ...

![ezgif-3-c10c332e24](https://user-images.githubusercontent.com/73824851/237032642-155f94e4-d281-4d66-beaf-40783e3a5697.gif)

in xcode it pop this
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/73824851/237033530-7a19c1f5-bce4-4966-a2ea-b552f3e9c790.png">

**Comment by philips77** [comment]
Thank you, I'll look into that next week.

**Comment by philips77** [comment]
Fixed. Thank you again for the excellent bug report! I wish all were like yours!
