### ISSUE TITLE
Incorrect units of pressure.

### ISSUE THREAD

**Issue by 0x0c** [NordicSemiconductor/IOS-nRF-Mesh-Library#507]
**Describe the bug**
A unit of pressure data is shown as ℃.

**To Reproduce**
You can find [here](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/main/nRFMeshProvision/Mesh%20Messages/DeviceProperty.swift#L1299)

**Expected behavior**
A unit of pressure data is shown as hPa.

**Platform details:**
   - Any devices
   - Any OS
 - Library Version (or Commit)
   - HEAD of main

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster

**Comment by philips77** [comment]
Nice catch!

**Comment by 0x0c** [comment]
@philips77 Thank you for your quick fix. I noticed the sensor value of pressure is notated as Pa not hPa, so we have to divide the value of the sensor by 100. Is my understanding correct?

https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/main/nRFMeshProvision/Mesh%20Messages/DeviceProperty.swift#L1163

**Comment by philips77** [comment]
I have to check it. Even if, my fix from yesterday prints it as hPa. I'll add a test for that and other similar cases.

**Comment by philips77** [comment]
The comment is copy-pasted from the spec for all characteristics. I suppose it will then be in Pascals. I need to fix the description, or divided there by 10.
