### ISSUE TITLE
build errors when using SPM

### ISSUE THREAD

**Issue by eanderlind** [NordicSemiconductor/IOS-nRF-Mesh-Library#522]
When building nRF Mesh using Swift Package Manager (SPM) instead of Pods in XCode 14.2 we 
encountered a few build errors (commit ed72bcd0e43d15787bbde5ab616b7969d7f3c2bd):
1. ProvisioningController.swift (missing a self for captured property)
2. Task.swift and TaskStatus.swift (missing import UIKit. Consider renaming Task, since the name clashes with Swift Concurrency Task)
3. We also got difficult to understand abi errors that we tracked down to the hardcoded assumption that Pods are used
In nRF Mesh.xcproj->Targets nRF Mesh: tab Build Phases ->[CP] Embed Pods Frameworks we had to comment out first line in the shell script (prepend with #) to get rid of these weird build errors. Is it possible to make this more user friendly so can choose how to manage packages?

Unclear if first 2 errors are dependent on XCode version or how packages managed.

Ps: Great updates to docs. Could be helpful to provide a pointer in ReadMe or Setting_Up.md how to create and access them.

**Comment by philips77** [comment]
Thanks for the feedback. I'll look into it.

Btw, somewhat big breaking changes are coming. I hope you're migrating slowly and using `main`, not the latest tagged version. There will be a lot to migrate, but it all for a good cause!

**Comment by philips77** [comment]
> ProvisioningController.swift (missing a self for captured property)

I can't find a file with this name.

**Comment by eanderlind** [comment]
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/fb18cecc37087f492c196c3e4c810040de600af4/Example/Source/View%20Controllers/Network/Provisioning/ProvisioningViewController.swift#L383C37-L383C37

**Comment by philips77** [comment]
How does it even compile?! Fixing!
