### ISSUE TITLE
Bind application key being applied to wrong model

### ISSUE THREAD

**Issue by do-dat-thang** [NordicSemiconductor/IOS-nRF-Mesh-Library#542]
**Describe the bug**
I have a device with 4 models within 1 element: config server and 3 onoff servers. When attempting to bind application keys to each of the onoff server models the keys always get bound to the first onoff server model. Application key binding seems to work fine and is a temporary work-around when the models are each in their own element.

**To Reproduce**
1. Change esp-idf onoff server example to have all models in the root_models[] element. And run. 
2. Add multiple application keys in the settings tab (I added 5).
2. Tap + on network tab
3. Select the ESP-BLE-MESH node
4. Tap provision and OK
5. Select the only element (Element 1)
6. Select each of the onoff server models and attempt to bind a unique application key to each.
7. Look at the first onoff server model and see that all the keys were bound to that one.
8. See on each of the other onoff server models there is no bound application key. 

**Expected behavior**
Each onoff server model will be bound to an application key and attempts to subscribe each will not fail with a pop up indicating a key must be bound.

**Platform details:**
 - Device: iPhone13
 - OS: iOS 16.6
 - Library Version (or Commit): what is this?? Latest nRF mesh from App Store ver 3.2.0 build 1

**Logs / Screenshots**
I don't see a log feature in the nRF mesh app.

**Comment by philips77** [comment]
Hello,

It is not allowed to have multiple instances of the same model in a single element.
If you want to have 3 instances of Generic On Off Server each of them has to he in a separate model, so your device needs to have 3 elements. The only way to identify a model is by Unicast Address (which element) and Model ID (which model type). There's no "instance" number therefore such case is forbidden by the spec.

> Application key binding seems to work fine and is a temporary work-around when the models are each in their own element.

This is not a temporary work-around, but it should be like that :) For a physical device with 3 buttons each such button is a different element.

> I don't see a log feature in the nRF mesh app.

Logs are available in *Console* app on a Mac when you have the iPhone connected to your Mac. The *Console* app is native on Mac and available out of the box, you just need to enabling logs for the connected device and enable INFO and DEBUG logs.
