### ISSUE TITLE
This is counting bits => should be counting bytes.

### ISSUE THREAD

**Issue by DomiR** [NordicSemiconductor/IOS-nRF-Mesh-Library#551]
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/3c6cde5f07929872d11542dd27441776bf697580/nRFMeshProvision/Mesh%20Messages/Time%20and%20Scenes/SchedulerActionStatus.swift#L56C18-L56C18

**Comment by philips77** [comment]
Great catch. Will fix soon.
