### ISSUE TITLE
Version 4.0.0 not sent vender mesages 

### ISSUE THREAD

**Issue by DuanPhan92** [NordicSemiconductor/IOS-nRF-Mesh-Library#568]
**Describe the bug**
I am using nrf mesh app on my iphone, yesterday everthing still ok. But today i can’t send any messages in vendor model.

**Platform details:**
 - Device: Iphone XS
 - OS: IOS16.6.1
 - Library Version 4.0.0

**Comment by philips77** [comment]
Thank you for the bug report. I'm in process of fixing bug, so I'll make sure to test and fix it.

Do you have any logs?

**Comment by philips77** [comment]
OK, I found the issue. `VendorMessage` is neither `AcknowledgedVendorMessage` nor `UnacknowledgedVendorMessage` and therefore is never sent. Will fix now!

**Comment by philips77** [comment]
Version 4.0.1 has been submitted to AppStore. Should be available soon.
Once again thank you for reporting the bug.
