### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by mostafaberg** [NordicSemiconductor/IOS-nRF-Mesh-Library#61]
As an *iOS 9 user*, I want to be able to run nRF Mesh on my device so that I can use mesh features on my device.

**Comment by Copypeng** [comment]
+1

**Comment by iDurian** [comment]
+1

**Comment by huangdaxiaEX** [comment]
+1

**Comment by philips77** [comment]
The new lib is available for iOS 9+. Only the sample app requires 10+. At least i hope so.

**Comment by huangdaxiaEX** [comment]
@philips77  Hi, thank you for your reply.

 I found the new lib source code use iOS 10+ API when received public key data [SecKeyCopyKeyExchangeResult](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/7cd48f4aeb04147cfb3aa1926c64afb65b3342f1/nRFMeshProvision/Classes/Provisioning/ProvisioningData.swift)

That can't work on iOS 9+.

**Comment by philips77** [comment]
Oh, great that you found this. Do you know any alternative we could use instead?

**Comment by philips77** [comment]
I guess we could try the OpenSSL lib...

**Comment by huangdaxiaEX** [comment]
Yes 👍 

OpenSSL lib provided it, I will try it.   :）

BTW,  the `SecKeyCopyKeyExchangeResult` works on iOS 13 will  receive an error "OSStatus-50- kSecKeyKeyExchangeParameterRequestedSize is missing". 

Need described `kSecKeyKeyExchangeParameterRequestedSize` length.

![image](https://user-images.githubusercontent.com/13418292/61614747-14c4ed00-ac97-11e9-8f23-a786cbd8c5dd.png)

**Comment by philips77** [comment]
Again, nice catch! Thanks!

**Comment by huangdaxiaEX** [comment]
@philips77 

I seem to have fixed it.

use 
`kSecKeyAlgorithmECDHKeyExchangeStandard` 
instead 
`kSecKeyAlgorithmECDHKeyExchangeStandardX963SHA256`

and

`exchangeResultParams` describe `kSecKeyKeyExchangeParameterRequestedSize : 32` 

The iOS 13+ will work fine.

**Comment by philips77** [comment]
Hi, could you check if it works on iOS 13 now with the latest changes?

**Comment by huangdaxiaEX** [comment]
I use iOS 13 beta.6, it works fine, thanks!
👍

**Comment by harendra23** [comment]
Hi,
I'm facing the same issue. regardless you pass parameter requestSize or not, iOS13 always has missing kSecKeyKeyExchangeParameterRequestedSize issue.
I tried on iOS beta 7, issue persist.
Could you please help me how to fix this issue?

Thanks,

**Comment by philips77** [comment]
Checking now.

**Comment by TuYuan** [comment]
Hi，philips 
     As an iOS 9 user, I want to be able to run nRF Mesh on my device so that I can use mesh features on my device. What should I do？

**Comment by philips77** [comment]
Hello,
For now, supporting iOS 9 is not our priority. This task is here for us to remember about this. As far as I remember there are just few features that are not supported on 9, and mainly in the sample app. But I may be wrong here.

**Comment by TuYuan** [comment]
Hi，philips
Can the new lib source code support iOS9? If supported, give a link. Thank you!

**Comment by philips77** [comment]
As iOS 9 is now many years old I'm closing this never-completed task.

**Comment by mostafaberg** [comment]
About time @philips77 ?😂
