### ISSUE TITLE
Heartbeat Messages

### ISSUE THREAD

**Issue by ahmadshoh-orc** [NordicSemiconductor/IOS-nRF-Mesh-Library#617]
### Version

4.2.0 (latest)

### Ask the question

I'm working on implementing Heartbeat logic in my application, but I'm encountering some issues with catching and processing incoming `HeartbeatMessages`.

Here's what I’ve done so far:

1. I sent a `ConfigHeartbeatPublicationSet` to the hardware and received a `ConfigHeartbeatPublicationStatus` indicating success.
2. However, when I try to retrieve the heartbeat data by sending a `ConfigHeartbeatPublicationGet`, I encounter a timeout.
3. In the logs, I see that `Heartbeat Messages` are being received every 15 seconds as expected, with entries like:

   ```
   Heartbeat Message (initial TTL: 8, received TTL: 7, hops: 2, features: [relay, proxy]) received from 000E
   ```

Despite this, I’m unable to catch these `HeartbeatMessages` in my application and perform the desired logic.

**What I Need Help With:**

- How can I correctly capture and process these `HeartbeatMessages`?
- Are there any specific configurations or code implementations required to handle these messages effectively?

Any guidance or examples on how to integrate this functionality would be greatly appreciated!

### Relevant log output

```text
* Configuration logs
Sending ConfigHeartbeatPublicationSet(networkKeyIndex: 0, destination: 1, countLog: 255, periodLog: 4, ttl: 8, features: [relay, proxy, friend, lowPower]) to: 0016
ConfigHeartbeatPublicationStatus(status: Success, networkKeyIndex: 0, destination: 1, countLog: 255, periodLog: 4, ttl: 8, features: [relay, proxy, friend, lowPower]) received from: 0016

* Trying to get HeartbeatPublicationStatus:
Sending ConfigHeartbeatPublicationGet() from: PrimaryElement (0x0001), to: 0016

Response to Access PDU (opcode: 0x8038, parameters: 0x) not received (timeout)
ConfigHeartbeatPublicationGet() sent from: 0001, to: 0016 timed out
Cancelling messages with op code: 32824, sent from: 0001 to: 0016
```

**Comment by philips77** [comment]
Hello,
You need to subscribe the local node to heartbeat messages by sending `ConfigHeartbeatSubscriptionSet` message:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/267216832aaa19ba6ffa1b49720a34fd3c2f8072/Example/Source/View%20Controllers/Network/Configuration/SetHeartbeatSubscriptionViewController.swift#L229-L251

When a heartbeat message is received it is being processed here:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/267216832aaa19ba6ffa1b49720a34fd3c2f8072/Library/Layers/Upper%20Transport%20Layer/UpperTransportLayer.swift#L248-L258
and the count is incremented only when the subscription is active.

To get the current count, send `ConfigHeartbeatSubscriptionGet` message to the local node, which will return the status message:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/267216832aaa19ba6ffa1b49720a34fd3c2f8072/Library/Layers/Foundation%20Layer/ConfigurationServerHandler.swift#L636-L637

Mind, that the implementation is based on the spec, so currently it's not possible to get a callback for every heartbeat message or obtain the exact count (log value is sent instead). It is also not possible to subscribe to more than one source at a time. There's an open task #470 which would improve it by adding designated callbacks.
