### ISSUE TITLE
The composition data features displayed in the mobile app is incorrect

### ISSUE THREAD

**Issue by zhiqiang6** [NordicSemiconductor/IOS-nRF-Mesh-Library#618]
### Where do you suspect the issue?

UI issue in nRF Mesh app, e.g. button is not clickable

### Version

4.2.0 (latest)

### Describe the issue

All other node information is parsed correctly. Expect all features to be enabled, but only the lower power feature is enabled. As a result, these features cannot be configured in the Configuration server.
![1](https://github.com/user-attachments/assets/ad60aba7-3dae-4f2c-919c-08f08fe71785)

**Comment by philips77** [comment]
Hello,
The _Composition Data Page 0_ contains a bitfield for "supported" features. It does not contain information whether the feature is enabled or not. For _Low Power_ feature the state is clear, as a Node is or isn't a Low Power Node (LPN), hence if the bit is marked, we can show Enabled (perhaps it should be Supported, or Yes).

For other features you need to go to the Main Element / Configuration Server and pull-to-refresh. This will send _Config ... Get_ for remaining features and the values will be updated with current values. It will then be possible to modify the state of these features.
