### ISSUE TITLE
Whether the ProvisionedMeshNodeDelegate can add Option support?

### ISSUE THREAD

**Issue by trusbe** [NordicSemiconductor/IOS-nRF-Mesh-Library#77]
**Is your feature request related to a problem? Please describe.**
As mentioned in the question, each time you call `ProvisionedMeshNodeDelegate.delegate = self` , you must say that all delegates are implemented in the file, even if many are not required;

**Describe the solution you'd like**
Add Option and Required support

**Additional context**
![1533865664394](https://user-images.githubusercontent.com/1946300/43934548-7acbd81e-9c82-11e8-8cb0-ea2e103c7dc8.jpg)

**Comment by mostafaberg** [comment]
This is not recommended, the node in any state should be able to respond to mesh messages in the future, so messages cannot be sent to  '/dev/null' ;) but I understand what you mean and there might be a better solution in the future , but for now, it's very important to be able to handle everything from each state. a proper router is needed though.
