### ISSUE TITLE
cocoapods error installing OpenSSL dependency

### ISSUE THREAD

**Issue by macellari-mac** [NordicSemiconductor/IOS-nRF-Mesh-Library#83]
Running 'pod install' I get an error during openssl dependency installation.

**To Reproduce**
run 'pod install'

**Expected behavior**
Verbose output terminating with:
cp: file.tgz: No such file or directory

It seems that the problem can be resolved changing the line:
    s.dependency 'OpenSSL'
to:
    s.dependency 'OpenSSL-Universal'
in the nRFMeshProvision.podspec file.

**Comment by trusbe** [comment]
look here: https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/issues/23

**Comment by mostafaberg** [comment]
This is fixed in the latest release, and the cocoapods is now released 👍!
to quickly test it out, please try to run the try command in your terminal
`pod try nRFMeshProvision`
