### ISSUE TITLE
Assigning wrong value for "supported input actions"

### ISSUE THREAD

**Issue by tyridw** [NordicSemiconductor/IOS-nRF-Mesh-Library#84]
I suppose a typo in the code caused the wrong value to be assigned:
`supportedInputActionsSubtitle.text = outputActions` should probably be `supportedInputActionsSubtitle.text = inputActions` at
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/e2ce5afbb89b2200c659927d3634dd1c0a0bdba5/Example/nRFMeshProvision/ViewControllers/ProvisioningView/MeshProvisioningDataTableViewController.swift#L595

**Comment by mostafaberg** [comment]
ahh of course!, good catch!
