### ISSUE TITLE
91% issue is back again

### ISSUE THREAD

**Issue by macellari-mac** [NordicSemiconductor/IOS-nRF-Mesh-Library#86]
**Describe the bug**
During node provisioning the process get stuck at 91% and stops.
The app needs to be terminated and the network db erased.

**To Reproduce**
1. Discovery new unprovisioned node
2. Change default name
3. Start provisioning
4. See error at 91%

**Expected behavior**
The provisioning process get stuck at 91%

**Platform details:**
 - Device: iPhone6s
 - OS: iOS11.4.1
 
**Logs / Screenshots**
![img_0159](https://user-images.githubusercontent.com/3061966/44922938-11ef9f80-ad47-11e8-8dbb-627f8cbb6804.PNG)
![img_0160](https://user-images.githubusercontent.com/3061966/44922946-17e58080-ad47-11e8-946f-4d27eddc75fa.PNG)
![img_0161](https://user-images.githubusercontent.com/3061966/44922951-1ae07100-ad47-11e8-94d2-ca0571a4e70d.PNG)
![img_0162](https://user-images.githubusercontent.com/3061966/44922954-1d42cb00-ad47-11e8-8195-0431c8fa6dc0.PNG)

**Comment by philips77** [comment]
Hi, the author of this app is on vacations so it may take few weeks before you'll get a response. Sorry for that!

**Comment by macellari-mac** [comment]
Hi Aleksander,

Mostafa is the only developer working on this iOS library?
Do you know when he will be back?

Lucio


Da: Aleksander Nowakowski [mailto:notifications@github.com]
Inviato: venerdì 31 agosto 2018 18:04
A: NordicSemiconductor/IOS-nRF-Mesh-Library
Cc: Lucio Macellari; Author
Oggetto: Re: [NordicSemiconductor/IOS-nRF-Mesh-Library] 91% issue is back again (#86)


Hi, the author of this app is on vacations so it may take few weeks before you'll get a response. Sorry for that!

**Comment by philips77** [comment]
He owns the iOS part, yes. He'll be back in 2 weeks, as far as I know. Did you try nRF Mesh on Android? Do you have similar problem?

**Comment by mostafaberg** [comment]
Issue is now resolved in the last PR, related to an TTL / acknowledgement issue that can only be resolved by a delay to wait for the retransmissions to be completed.

**Comment by mostafaberg** [comment]
fix will be in the next release, for now it's on the develop branch 👍

**Comment by tyridw** [comment]
:+1:
