### ISSUE TITLE
hello,I'd like to ask you a question

### ISSUE THREAD

**Issue by Deepblue1996** [NordicSemiconductor/IOS-nRF-Mesh-Library#88]
I want to achieve ios background bluetooth broadcast data transmission，I looked for information on the Internet，plist File Required background modes item add App communicates using CoreBluetooth and App shares data using CoreBluetooth.I have solved the background program to stop running, but bluetooth is not broadcast out.

**Comment by mostafaberg** [comment]
This is probably not really related to Bluetooth Mesh nor this library, I recommend opening a question on our DevZone where others will surely help :)
